import json

# Additional girl names to supplement the dataset
# Focusing on categories not yet well covered

additional_girls = [
    # ---- MORE CLASSIC AMERICAN / ENGLISH ----
    {"name": "Mary", "meaning": "Hebrew origin, meaning 'beloved' or 'bitter'"},
    {"name": "Patricia", "meaning": "Latin origin, meaning 'noblewoman'"},
    {"name": "Linda", "meaning": "Spanish origin, meaning 'pretty' or 'beautiful'"},
    {"name": "Barbara", "meaning": "Greek origin, meaning 'foreign woman' or 'stranger'"},
    {"name": "Elizabeth", "meaning": "Hebrew origin, meaning 'my God is an oath'"},
    {"name": "Jennifer", "meaning": "Cornish form of Guinevere, meaning 'white shadow'"},
    {"name": "Maria", "meaning": "Latin form of Mary, meaning 'beloved' or 'bitter'"},
    {"name": "Susan", "meaning": "Hebrew origin, meaning 'lily' or 'rose'"},
    {"name": "Margaret", "meaning": "Greek origin, meaning 'pearl'"},
    {"name": "Dorothy", "meaning": "Greek origin, meaning 'gift of God'"},
    {"name": "Lisa", "meaning": "Hebrew origin, short form of Elizabeth, meaning 'God's oath'"},
    {"name": "Nancy", "meaning": "Hebrew origin, form of Anne, meaning 'grace'"},
    {"name": "Karen", "meaning": "Danish form of Katherine, meaning 'pure'"},
    {"name": "Betty", "meaning": "Hebrew origin, short form of Elizabeth, meaning 'God's oath'"},
    {"name": "Helen", "meaning": "Greek origin, meaning 'torch' or 'shining light'"},
    {"name": "Sandra", "meaning": "Greek origin, short form of Alexandra, meaning 'defender of men'"},
    {"name": "Donna", "meaning": "Italian origin, meaning 'lady' or 'woman'"},
    {"name": "Carol", "meaning": "Old Germanic origin, meaning 'free woman'"},
    {"name": "Ruth", "meaning": "Hebrew origin, meaning 'companion' or 'friend'"},
    {"name": "Sharon", "meaning": "Hebrew origin, meaning 'a plain' or 'flat area'"},
    {"name": "Michelle", "meaning": "French form of Michael, meaning 'who is like God?'"},
    {"name": "Laura", "meaning": "Latin origin, meaning 'bay laurel tree'"},
    {"name": "Sarah", "meaning": "Hebrew origin, meaning 'princess' or 'noblewoman'"},
    {"name": "Kimberly", "meaning": "Old English origin, meaning 'from the meadow of the royal fortress'"},
    {"name": "Deborah", "meaning": "Hebrew origin, meaning 'bee'"},
    {"name": "Jessica", "meaning": "Hebrew origin, meaning 'God beholds'"},
    {"name": "Shirley", "meaning": "Old English origin, meaning 'bright meadow'"},
    {"name": "Angela", "meaning": "Latin origin, meaning 'messenger' or 'angel'"},
    {"name": "Melissa", "meaning": "Greek origin, meaning 'honeybee'"},
    {"name": "Brenda", "meaning": "Old Norse origin, meaning 'sword blade'"},
    {"name": "Amy", "meaning": "Old French origin, meaning 'beloved'"},
    {"name": "Anna", "meaning": "Hebrew origin, form of Hannah, meaning 'grace'"},
    {"name": "Rebecca", "meaning": "Hebrew origin, meaning 'to bind' or 'snare'"},
    {"name": "Virginia", "meaning": "Latin origin, meaning 'pure' or 'virgin'"},
    {"name": "Kathleen", "meaning": "Irish form of Katherine, meaning 'pure'"},
    {"name": "Pamela", "meaning": "Greek origin, invented by Philip Sidney, meaning 'all honey'"},
    {"name": "Martha", "meaning": "Aramaic origin, meaning 'lady' or 'mistress'"},
    {"name": "Cheryl", "meaning": "French and Welsh origin, meaning 'beloved'"},
    {"name": "Carolyn", "meaning": "Old Germanic origin, meaning 'free woman'"},
    {"name": "Janet", "meaning": "Hebrew origin, form of Jane, meaning 'God is gracious'"},
    {"name": "Diane", "meaning": "Latin origin, Roman goddess of the moon"},
    {"name": "Christine", "meaning": "Latin origin, meaning 'follower of Christ'"},
    {"name": "Cynthia", "meaning": "Greek origin, from Mount Cynthus, epithet of Artemis"},
    {"name": "Judith", "meaning": "Hebrew origin, meaning 'woman from Judea'"},
    {"name": "Joan", "meaning": "Hebrew origin, form of John, meaning 'God is gracious'"},
    {"name": "Carolyn", "meaning": "Old Germanic origin, meaning 'free woman'"},
    {"name": "Denise", "meaning": "Greek origin, feminine of Denis, meaning 'follower of Dionysus'"},
    {"name": "Theresa", "meaning": "Greek origin, meaning 'to harvest' or 'summer'"},
    {"name": "Kathryn", "meaning": "Greek origin, meaning 'pure'"},
    {"name": "Janice", "meaning": "Hebrew origin, feminine of John, meaning 'God is gracious'"},
    {"name": "Marilyn", "meaning": "Hebrew origin, combination of Mary and Lynn, meaning 'sea lake'"},
    {"name": "Tammy", "meaning": "Hebrew origin, short for Tamara, meaning 'palm tree'"},
    {"name": "Robin", "meaning": "Old Germanic origin, meaning 'bright fame'"},
    {"name": "Gloria", "meaning": "Latin origin, meaning 'glory'"},
    {"name": "Wanda", "meaning": "Old Germanic origin, meaning 'wanderer'"},
    {"name": "Phyllis", "meaning": "Greek origin, meaning 'green branch' or 'foliage'"},
    {"name": "Norma", "meaning": "Latin origin, meaning 'normal' or 'rule'"},
    {"name": "Paula", "meaning": "Latin origin, feminine of Paul, meaning 'small'"},
    {"name": "Diana", "meaning": "Latin origin, Roman goddess of the moon, meaning 'divine'"},
    {"name": "Tina", "meaning": "Latin origin, short form of Christina, meaning 'follower of Christ'"},
    {"name": "Edna", "meaning": "Hebrew origin, meaning 'rejuvenation' or 'pleasure'"},
    {"name": "Doris", "meaning": "Greek origin, meaning 'gift' or 'from Doris'"},
    {"name": "Peggy", "meaning": "Greek origin, nickname for Margaret, meaning 'pearl'"},
    {"name": "Gail", "meaning": "Hebrew origin, short form of Abigail, meaning 'father rejoices'"},
    {"name": "Marcia", "meaning": "Latin origin, feminine of Marcus, meaning 'of Mars'"},
    {"name": "Paula", "meaning": "Latin origin, feminine of Paul, meaning 'small'"},
    {"name": "Rhonda", "meaning": "Welsh origin, meaning 'noisy river'"},
    {"name": "Beverly", "meaning": "Old English origin, meaning 'beaver stream'"},
    {"name": "Bonnie", "meaning": "Scottish origin, meaning 'attractive' or 'cheerful'"},
    {"name": "Valerie", "meaning": "Latin origin, meaning 'strength' or 'health'"},
    {"name": "Sheila", "meaning": "Irish form of Cecilia, meaning 'blind'"},
    {"name": "Marjorie", "meaning": "French form of Margaret, meaning 'pearl'"},
    {"name": "Eileen", "meaning": "Irish form of Helen, meaning 'shining light'"},
    {"name": "Lois", "meaning": "Greek origin, meaning 'more desirable' or 'better'"},
    {"name": "Marianne", "meaning": "French combination of Marie and Anne, meaning 'grace'"},
    {"name": "Beverly", "meaning": "Old English origin, meaning 'beaver stream'"},
    {"name": "Gloria", "meaning": "Latin origin, meaning 'glory'"},
    {"name": "Thelma", "meaning": "Greek origin, meaning 'will' or 'volition'"},
    {"name": "Frances", "meaning": "Latin origin, meaning 'from France' or 'free'"},

    # ---- MORE MODERN / POPULAR ----
    {"name": "Emma", "meaning": "Old Germanic origin, meaning 'whole' or 'universal'"},
    {"name": "Olivia", "meaning": "Latin origin, meaning 'olive tree' symbolizing peace"},
    {"name": "Ava", "meaning": "Latin or Hebrew origin, meaning 'bird' or 'life'"},
    {"name": "Isabella", "meaning": "Hebrew origin via Spanish, meaning 'God is my oath'"},
    {"name": "Sophia", "meaning": "Greek origin, meaning 'wisdom'"},
    {"name": "Charlotte", "meaning": "French form of Charles, meaning 'free woman'"},
    {"name": "Mia", "meaning": "Scandinavian and Italian origin, meaning 'mine' or 'beloved'"},
    {"name": "Amelia", "meaning": "Old Germanic origin, meaning 'work' or 'industrious'"},
    {"name": "Harper", "meaning": "Old English occupational name meaning 'harp player'"},
    {"name": "Evelyn", "meaning": "English origin, meaning 'hazelnut' or 'wished for child'"},
    {"name": "Abigail", "meaning": "Hebrew origin, meaning 'my father rejoices'"},
    {"name": "Emily", "meaning": "Latin origin, meaning 'rival' or 'to excel'"},
    {"name": "Ella", "meaning": "Old Germanic origin, meaning 'all' or 'completely'"},
    {"name": "Chloe", "meaning": "Greek origin, meaning 'blooming' or 'young green shoot'"},
    {"name": "Penelope", "meaning": "Greek origin, meaning 'weaver' or 'duck'"},
    {"name": "Grace", "meaning": "Latin origin, meaning 'grace' or 'favor of God'"},
    {"name": "Scarlett", "meaning": "Old French origin, meaning 'red' or 'scarlet cloth'"},
    {"name": "Madison", "meaning": "Old English origin, meaning 'son of Maud'"},
    {"name": "Victoria", "meaning": "Latin origin, meaning 'victory'"},
    {"name": "Aria", "meaning": "Italian and Hebrew origin, meaning 'air' or 'song'"},
    {"name": "Lily", "meaning": "Latin origin, from the lily flower symbolizing purity"},
    {"name": "Nora", "meaning": "Irish and Latin origin, meaning 'honor' or 'light'"},
    {"name": "Eleanor", "meaning": "Greek and French origin, meaning 'bright' or 'shining one'"},
    {"name": "Hannah", "meaning": "Hebrew origin, meaning 'grace' or 'favor'"},
    {"name": "Lillian", "meaning": "Latin origin, meaning 'lily' symbolizing purity"},
    {"name": "Addison", "meaning": "Old English origin, meaning 'son of Adam'"},
    {"name": "Aubrey", "meaning": "Old Germanic origin, meaning 'elf ruler'"},
    {"name": "Ellie", "meaning": "Greek origin, short form of Eleanor, meaning 'bright'"},
    {"name": "Stella", "meaning": "Latin origin, meaning 'star'"},
    {"name": "Natalie", "meaning": "Latin origin, meaning 'born at Christmas'"},
    {"name": "Leah", "meaning": "Hebrew origin, meaning 'weary' or 'delicate'"},
    {"name": "Hazel", "meaning": "Old English nature name referring to the hazel tree"},
    {"name": "Violet", "meaning": "Latin origin, from the violet flower meaning 'purple'"},
    {"name": "Aurora", "meaning": "Latin origin, meaning 'dawn'"},
    {"name": "Savannah", "meaning": "Spanish origin, meaning 'flat tropical grassland'"},
    {"name": "Audrey", "meaning": "Old English origin, meaning 'noble strength'"},
    {"name": "Brooklyn", "meaning": "Dutch origin, meaning 'broken land'"},
    {"name": "Bella", "meaning": "Italian and Latin origin, meaning 'beautiful'"},
    {"name": "Claire", "meaning": "Latin origin, meaning 'clear' or 'bright'"},
    {"name": "Skylar", "meaning": "Dutch origin, meaning 'scholar'"},
    {"name": "Lucy", "meaning": "Latin origin, meaning 'light'"},
    {"name": "Paisley", "meaning": "Scottish place name, meaning 'church'"},
    {"name": "Everly", "meaning": "Old English origin, meaning 'wild boar meadow'"},
    {"name": "Anna", "meaning": "Hebrew origin, meaning 'grace' or 'favor'"},
    {"name": "Caroline", "meaning": "French form of Charles, meaning 'free woman'"},
    {"name": "Genesis", "meaning": "Greek origin, meaning 'origin' or 'beginning'"},
    {"name": "Kennedy", "meaning": "Irish origin, meaning 'armored head'"},
    {"name": "Samantha", "meaning": "Hebrew origin, possibly meaning 'told by God'"},
    {"name": "Aaliyah", "meaning": "Arabic origin, meaning 'high' or 'exalted'"},
    {"name": "Layla", "meaning": "Arabic origin, meaning 'night' or 'dark beauty'"},
    {"name": "Ivy", "meaning": "Old English nature name referring to the climbing ivy plant"},
    {"name": "Willow", "meaning": "Old English nature name referring to the willow tree"},
    {"name": "Zoe", "meaning": "Greek origin, meaning 'life'"},
    {"name": "Lilliana", "meaning": "Latin origin, extended form of Lily, meaning 'pure'"},
    {"name": "Natalia", "meaning": "Latin origin, meaning 'born at Christmas'"},
    {"name": "Kinsley", "meaning": "Old English origin, meaning 'king's meadow'"},
    {"name": "Madeline", "meaning": "Greek origin, meaning 'woman from Magdala'"},
    {"name": "Sofia", "meaning": "Greek origin, meaning 'wisdom'"},
    {"name": "Adeline", "meaning": "Old Germanic origin, meaning 'noble' or 'nobility'"},
    {"name": "Quinn", "meaning": "Irish origin, meaning 'counsel' or 'intelligence'"},
    {"name": "Ruby", "meaning": "Latin origin, from the red gemstone meaning 'red'"},
    {"name": "Eva", "meaning": "Hebrew origin, meaning 'life' or 'living'"},
    {"name": "Maya", "meaning": "Hebrew and Sanskrit origin, meaning 'water' or 'illusion'"},
    {"name": "Kylie", "meaning": "Australian Aboriginal origin, meaning 'boomerang'"},
    {"name": "Peyton", "meaning": "Old English origin, meaning 'fighting man's estate'"},
    {"name": "Mackenzie", "meaning": "Scottish Gaelic origin, meaning 'son of Kenneth'"},
    {"name": "Alexis", "meaning": "Greek origin, meaning 'defender'"},
    {"name": "Gianna", "meaning": "Italian form of Jane, meaning 'God is gracious'"},
    {"name": "Jasmine", "meaning": "Persian origin, from the jasmine flower"},
    {"name": "Serenity", "meaning": "English origin, meaning 'peaceful' or 'tranquil'"},
    {"name": "Annabelle", "meaning": "Hebrew and French origin, meaning 'grace and beauty'"},
    {"name": "Ariana", "meaning": "Italian form of Adriana, meaning 'from Hadria'"},
    {"name": "Autumn", "meaning": "Latin origin, referring to the fall season"},
    {"name": "Hailey", "meaning": "Old English origin, meaning 'hay meadow'"},
    {"name": "Kaylee", "meaning": "Irish and Hebrew origin, meaning 'pure' or 'slender'"},
    {"name": "Piper", "meaning": "Old English occupational name meaning 'flute player'"},
    {"name": "Taylor", "meaning": "Old French occupational name meaning 'tailor'"},
    {"name": "Alyssa", "meaning": "Greek origin, from the alyssum flower, meaning 'rational'"},
    {"name": "Lydia", "meaning": "Greek origin, meaning 'woman from Lydia'"},
    {"name": "Ashley", "meaning": "Old English origin, meaning 'ash tree meadow'"},
    {"name": "Jade", "meaning": "Spanish origin, from the gemstone meaning 'stone of the side'"},
    {"name": "Katherine", "meaning": "Greek origin, meaning 'pure'"},
    {"name": "Sydney", "meaning": "Old English origin, meaning 'wide island'"},
    {"name": "Naomi", "meaning": "Hebrew origin, meaning 'pleasant' or 'beautiful'"},
    {"name": "Alexandra", "meaning": "Greek origin, meaning 'defender of men'"},
    {"name": "Brielle", "meaning": "Hebrew origin, short form of Gabrielle, meaning 'God is my strength'"},
    {"name": "Reagan", "meaning": "Irish origin, meaning 'little king'"},
    {"name": "Allison", "meaning": "Old Germanic origin, meaning 'noble' or 'nobility'"},
    {"name": "Brianna", "meaning": "Irish origin, feminine of Brian, meaning 'strong'"},
    {"name": "Amber", "meaning": "Arabic origin, from the gemstone meaning 'amber'"},
    {"name": "Destiny", "meaning": "Latin origin, meaning 'fate' or 'fortune'"},
    {"name": "Trinity", "meaning": "Latin origin, meaning 'three' or 'the Holy Trinity'"},
    {"name": "Morgan", "meaning": "Welsh origin, meaning 'sea circle'"},
    {"name": "Paige", "meaning": "Old French origin, meaning 'young servant'"},
    {"name": "Sadie", "meaning": "Hebrew origin, nickname for Sarah, meaning 'princess'"},
    {"name": "Brooke", "meaning": "Old English origin, meaning 'near a brook'"},
    {"name": "Cora", "meaning": "Greek origin, meaning 'maiden'"},
    {"name": "Reagan", "meaning": "Irish origin, meaning 'little king'"},
    {"name": "Teagan", "meaning": "Irish origin, meaning 'beautiful' or 'poet'"},
    {"name": "Riley", "meaning": "Irish origin, meaning 'courageous'"},
    {"name": "Camille", "meaning": "Latin origin, meaning 'ceremonial attendant'"},
    {"name": "Naomi", "meaning": "Hebrew origin, meaning 'pleasant'"},
    {"name": "Alexia", "meaning": "Greek origin, meaning 'defender'"},
    {"name": "Melanie", "meaning": "Greek origin, meaning 'dark' or 'black'"},
    {"name": "Sloane", "meaning": "Irish origin, meaning 'warrior'"},
    {"name": "Addyson", "meaning": "Modern variant of Addison, meaning 'son of Adam'"},

    # ---- BIBLICAL GIRL NAMES ----
    {"name": "Abigail", "meaning": "Hebrew origin, meaning 'my father rejoices'"},
    {"name": "Bathsheba", "meaning": "Hebrew origin, meaning 'daughter of the oath'"},
    {"name": "Deborah", "meaning": "Hebrew origin, meaning 'bee'"},
    {"name": "Delilah", "meaning": "Hebrew origin, meaning 'delicate' or 'weak'"},
    {"name": "Dinah", "meaning": "Hebrew origin, meaning 'judged' or 'vindicated'"},
    {"name": "Esther", "meaning": "Persian origin, meaning 'star'"},
    {"name": "Eunice", "meaning": "Greek origin, meaning 'good victory'"},
    {"name": "Hagar", "meaning": "Hebrew origin, meaning 'forsaken' or 'flight'"},
    {"name": "Jemima", "meaning": "Hebrew origin, meaning 'dove'"},
    {"name": "Kezia", "meaning": "Hebrew origin, meaning 'cassia tree'"},
    {"name": "Lydia", "meaning": "Greek origin, meaning 'woman from Lydia'"},
    {"name": "Miriam", "meaning": "Hebrew origin, meaning 'beloved' or 'sea of bitterness'"},
    {"name": "Naomi", "meaning": "Hebrew origin, meaning 'pleasant'"},
    {"name": "Priscilla", "meaning": "Latin origin, meaning 'ancient' or 'venerable'"},
    {"name": "Rachel", "meaning": "Hebrew origin, meaning 'ewe' or 'female sheep'"},
    {"name": "Rahab", "meaning": "Hebrew origin, meaning 'wide' or 'spacious'"},
    {"name": "Rebecca", "meaning": "Hebrew origin, meaning 'to bind' or 'snare'"},
    {"name": "Rizpah", "meaning": "Hebrew origin, meaning 'hot stone'"},
    {"name": "Sapphira", "meaning": "Greek and Hebrew origin, meaning 'beautiful'"},
    {"name": "Shulamith", "meaning": "Hebrew origin, meaning 'peaceful'"},
    {"name": "Tamar", "meaning": "Hebrew origin, meaning 'palm tree'"},
    {"name": "Zilpah", "meaning": "Hebrew origin, meaning 'trickling'"},
    {"name": "Zipporah", "meaning": "Hebrew origin, meaning 'bird'"},
    {"name": "Damaris", "meaning": "Greek origin, meaning 'calf' or 'gentle'"},
    {"name": "Phoebe", "meaning": "Greek origin, meaning 'bright' or 'pure'"},
    {"name": "Dorcas", "meaning": "Greek origin, meaning 'gazelle'"},
    {"name": "Joanna", "meaning": "Hebrew origin, meaning 'God is gracious'"},
    {"name": "Susanna", "meaning": "Hebrew origin, meaning 'lily'"},
    {"name": "Tabitha", "meaning": "Aramaic origin, meaning 'gazelle'"},
    {"name": "Bernice", "meaning": "Greek origin, meaning 'bringing victory'"},
    {"name": "Tirzah", "meaning": "Hebrew origin, meaning 'pleasantness'"},

    # ---- NORSE GIRL NAMES ----
    {"name": "Freya", "meaning": "Old Norse origin, name of the goddess of love and beauty"},
    {"name": "Astrid", "meaning": "Old Norse origin, meaning 'divinely beautiful'"},
    {"name": "Sigrid", "meaning": "Old Norse origin, meaning 'victory beauty'"},
    {"name": "Ragnhild", "meaning": "Old Norse origin, meaning 'battle might'"},
    {"name": "Ingrid", "meaning": "Old Norse origin, meaning 'Ing's beauty'"},
    {"name": "Solveig", "meaning": "Old Norse origin, meaning 'sun strength'"},
    {"name": "Gudrun", "meaning": "Old Norse origin, meaning 'divine rune'"},
    {"name": "Brynnhildr", "meaning": "Old Norse origin, meaning 'armor battle'"},
    {"name": "Sif", "meaning": "Old Norse origin, name of Thor's wife, meaning 'bride'"},
    {"name": "Hilde", "meaning": "Old Norse and Germanic origin, meaning 'battle'"},
    {"name": "Ulfhild", "meaning": "Old Norse origin, meaning 'wolf battle'"},
    {"name": "Vigdis", "meaning": "Old Norse origin, meaning 'battle goddess'"},
    {"name": "Thyra", "meaning": "Old Norse origin, meaning 'Thor's battle'"},
    {"name": "Randi", "meaning": "Old Norse origin, meaning 'shield' or 'high place'"},
    {"name": "Nanna", "meaning": "Old Norse origin, wife of Baldr, meaning 'daring'"},
    {"name": "Gerd", "meaning": "Old Norse origin, a frost giantess, meaning 'enclosure'"},
    {"name": "Freyja", "meaning": "Old Norse origin, the full form of Freya, meaning 'lady'"},
    {"name": "Bodil", "meaning": "Old Norse origin, meaning 'commanding'"},
    {"name": "Alvilda", "meaning": "Old Norse origin, meaning 'elf battle'"},
    {"name": "Asdis", "meaning": "Old Norse origin, meaning 'divine goddess'"},

    # ---- CELTIC / IRISH GIRL NAMES ----
    {"name": "Aoife", "meaning": "Irish origin, meaning 'beautiful' or 'radiant'"},
    {"name": "Niamh", "meaning": "Irish origin, meaning 'bright' or 'radiant'"},
    {"name": "Siobhan", "meaning": "Irish form of Joan, meaning 'God is gracious'"},
    {"name": "Grainne", "meaning": "Irish origin, meaning 'grain' or 'sun'"},
    {"name": "Brigid", "meaning": "Irish origin, name of the goddess of fire, meaning 'exalted'"},
    {"name": "Clodagh", "meaning": "Irish origin, from the River Clodagh"},
    {"name": "Deirdre", "meaning": "Irish origin, meaning 'sorrowful'"},
    {"name": "Eithne", "meaning": "Irish origin, meaning 'kernel' or 'grain'"},
    {"name": "Fionnula", "meaning": "Irish origin, meaning 'white shoulder'"},
    {"name": "Ide", "meaning": "Irish origin, meaning 'thirst'"},
    {"name": "Meadhbh", "meaning": "Irish origin, meaning 'intoxicating'"},
    {"name": "Muireann", "meaning": "Irish origin, meaning 'sea white' or 'sea fair'"},
    {"name": "Orlaith", "meaning": "Irish origin, meaning 'golden princess'"},
    {"name": "Roisin", "meaning": "Irish origin, meaning 'little rose'"},
    {"name": "Sadhbh", "meaning": "Irish origin, meaning 'sweet' or 'goodly'"},
    {"name": "Sorcha", "meaning": "Irish origin, meaning 'brightness' or 'radiance'"},
    {"name": "Una", "meaning": "Irish origin, meaning 'unity' or 'lamb'"},
    {"name": "Aine", "meaning": "Irish origin, name of the sun goddess, meaning 'radiance'"},
    {"name": "Brid", "meaning": "Irish form of Bridget, meaning 'exalted one'"},
    {"name": "Caoimhe", "meaning": "Irish origin, meaning 'gentle' or 'beautiful'"},
    {"name": "Caitlin", "meaning": "Irish form of Catherine, meaning 'pure'"},
    {"name": "Sinead", "meaning": "Irish form of Jane, meaning 'God is gracious'"},
    {"name": "Fiona", "meaning": "Scottish Gaelic origin, meaning 'white' or 'fair'"},
    {"name": "Morag", "meaning": "Scottish Gaelic origin, meaning 'great'"},
    {"name": "Eilidh", "meaning": "Scottish Gaelic origin, meaning 'radiant one'"},
    {"name": "Rhiannon", "meaning": "Welsh origin, from a Celtic goddess, meaning 'divine queen'"},
    {"name": "Branwen", "meaning": "Welsh origin, meaning 'blessed raven'"},
    {"name": "Cerridwen", "meaning": "Welsh origin, name of goddess of inspiration"},
    {"name": "Gwenllian", "meaning": "Welsh origin, meaning 'white linen'"},
    {"name": "Seren", "meaning": "Welsh origin, meaning 'star'"},

    # ---- ARABIC GIRL NAMES ----
    {"name": "Leila", "meaning": "Arabic origin, meaning 'night' or 'dark beauty'"},
    {"name": "Fatima", "meaning": "Arabic origin, meaning 'captivating' or 'abstainer'"},
    {"name": "Aisha", "meaning": "Arabic origin, meaning 'she who lives' or 'alive'"},
    {"name": "Amira", "meaning": "Arabic origin, meaning 'princess' or 'commander'"},
    {"name": "Nadia", "meaning": "Slavic and Arabic origin, meaning 'hope'"},
    {"name": "Yasmin", "meaning": "Arabic origin, meaning 'jasmine flower'"},
    {"name": "Zainab", "meaning": "Arabic origin, meaning 'fragrant flowering plant'"},
    {"name": "Rania", "meaning": "Arabic origin, meaning 'gazing' or 'queen'"},
    {"name": "Mariam", "meaning": "Arabic form of Mary, meaning 'beloved'"},
    {"name": "Hanan", "meaning": "Arabic origin, meaning 'mercy' or 'compassion'"},
    {"name": "Samira", "meaning": "Arabic origin, meaning 'entertaining companion'"},
    {"name": "Dina", "meaning": "Hebrew and Arabic origin, meaning 'judged'"},
    {"name": "Hind", "meaning": "Arabic origin, meaning 'group of camels'"},
    {"name": "Laila", "meaning": "Arabic origin, meaning 'night'"},
    {"name": "Lamia", "meaning": "Arabic origin, meaning 'shining' or 'radiant'"},
    {"name": "Lubna", "meaning": "Arabic origin, meaning 'storax tree'"},
    {"name": "Maha", "meaning": "Arabic origin, meaning 'large eyes of a gazelle'"},
    {"name": "Manal", "meaning": "Arabic origin, meaning 'attainment' or 'achievement'"},
    {"name": "Noor", "meaning": "Arabic origin, meaning 'light'"},
    {"name": "Nuha", "meaning": "Arabic origin, meaning 'intelligence' or 'mind'"},
    {"name": "Reem", "meaning": "Arabic origin, meaning 'gazelle'"},
    {"name": "Ruba", "meaning": "Arabic origin, meaning 'hills' or 'prosperity'"},
    {"name": "Salma", "meaning": "Arabic origin, meaning 'peaceful' or 'safe'"},
    {"name": "Sana", "meaning": "Arabic origin, meaning 'radiance' or 'brilliance'"},
    {"name": "Sara", "meaning": "Hebrew and Arabic origin, meaning 'princess'"},
    {"name": "Shahd", "meaning": "Arabic origin, meaning 'honey' or 'nectar'"},
    {"name": "Siham", "meaning": "Arabic origin, meaning 'arrows'"},
    {"name": "Suha", "meaning": "Arabic origin, meaning 'forgotten star'"},
    {"name": "Wafa", "meaning": "Arabic origin, meaning 'loyalty' or 'faithfulness'"},
    {"name": "Widad", "meaning": "Arabic origin, meaning 'love' or 'affection'"},

    # ---- HEBREW GIRL NAMES ----
    {"name": "Adina", "meaning": "Hebrew origin, meaning 'gentle' or 'slender'"},
    {"name": "Aliza", "meaning": "Hebrew origin, meaning 'joyful'"},
    {"name": "Avital", "meaning": "Hebrew origin, meaning 'father of dew'"},
    {"name": "Batya", "meaning": "Hebrew origin, meaning 'daughter of God'"},
    {"name": "Chana", "meaning": "Hebrew origin, meaning 'grace' or 'favor'"},
    {"name": "Dalya", "meaning": "Hebrew origin, meaning 'branch' or 'vine'"},
    {"name": "Devora", "meaning": "Hebrew origin, meaning 'bee'"},
    {"name": "Efrat", "meaning": "Hebrew origin, meaning 'fruitful'"},
    {"name": "Galit", "meaning": "Hebrew origin, meaning 'wave'"},
    {"name": "Gilat", "meaning": "Hebrew origin, meaning 'my joy'"},
    {"name": "Hadassah", "meaning": "Hebrew origin, meaning 'myrtle tree'"},
    {"name": "Hila", "meaning": "Hebrew origin, meaning 'praise' or 'glory'"},
    {"name": "Ilana", "meaning": "Hebrew origin, meaning 'tree'"},
    {"name": "Kinneret", "meaning": "Hebrew origin, name of the Sea of Galilee"},
    {"name": "Liora", "meaning": "Hebrew origin, meaning 'I have light'"},
    {"name": "Michal", "meaning": "Hebrew origin, meaning 'who is like God'"},
    {"name": "Noa", "meaning": "Hebrew origin, meaning 'motion' or 'movement'"},
    {"name": "Ofra", "meaning": "Hebrew origin, meaning 'fawn'"},
    {"name": "Orly", "meaning": "Hebrew origin, meaning 'my light'"},
    {"name": "Rona", "meaning": "Hebrew origin, meaning 'my joy'"},
    {"name": "Ronit", "meaning": "Hebrew origin, meaning 'song' or 'joy'"},
    {"name": "Shira", "meaning": "Hebrew origin, meaning 'song' or 'poem'"},
    {"name": "Talia", "meaning": "Hebrew origin, meaning 'dew from God'"},
    {"name": "Tamar", "meaning": "Hebrew origin, meaning 'palm tree'"},
    {"name": "Tikva", "meaning": "Hebrew origin, meaning 'hope'"},
    {"name": "Yael", "meaning": "Hebrew origin, meaning 'ibex' or 'mountain goat'"},
    {"name": "Yonit", "meaning": "Hebrew origin, meaning 'dove'"},
    {"name": "Zohar", "meaning": "Hebrew origin, meaning 'radiance' or 'brilliant light'"},

    # ---- LATIN / ROMAN GIRL NAMES ----
    {"name": "Aelia", "meaning": "Latin origin, meaning 'sun'"},
    {"name": "Antonia", "meaning": "Latin origin, feminine of Anthony, meaning 'priceless one'"},
    {"name": "Aurelia", "meaning": "Latin origin, meaning 'golden'"},
    {"name": "Caelia", "meaning": "Latin origin, meaning 'heavenly'"},
    {"name": "Camilla", "meaning": "Latin origin, meaning 'ceremonial attendant'"},
    {"name": "Cassia", "meaning": "Latin origin, from the cinnamon-like spice plant"},
    {"name": "Claudia", "meaning": "Latin origin, feminine of Claudius, meaning 'lame'"},
    {"name": "Cornelia", "meaning": "Latin origin, feminine of Cornelius, meaning 'horn'"},
    {"name": "Flavia", "meaning": "Latin origin, meaning 'golden-haired'"},
    {"name": "Lavinia", "meaning": "Latin origin, meaning 'woman from Lavinium'"},
    {"name": "Livia", "meaning": "Latin origin, meaning 'blue' or 'envious'"},
    {"name": "Lucia", "meaning": "Latin origin, meaning 'light'"},
    {"name": "Lucrezia", "meaning": "Latin origin, meaning 'wealth'"},
    {"name": "Octavia", "meaning": "Latin origin, meaning 'eighth'"},
    {"name": "Portia", "meaning": "Latin origin, meaning 'pig' or 'doorway'"},
    {"name": "Valentina", "meaning": "Latin origin, meaning 'strong' or 'healthy'"},
    {"name": "Verginia", "meaning": "Latin origin, meaning 'pure'"},
    {"name": "Celia", "meaning": "Latin origin, meaning 'heavenly'"},
    {"name": "Julia", "meaning": "Latin origin, feminine of Julius, meaning 'youthful'"},
    {"name": "Silvia", "meaning": "Latin origin, meaning 'forest' or 'woods'"},
    {"name": "Maxima", "meaning": "Latin origin, feminine of Maximus, meaning 'greatest'"},

    # ---- GREEK GIRL NAMES ----
    {"name": "Athena", "meaning": "Greek origin, name of the goddess of wisdom"},
    {"name": "Persephone", "meaning": "Greek origin, goddess of spring, meaning 'bringer of death'"},
    {"name": "Calliope", "meaning": "Greek origin, muse of poetry, meaning 'beautiful voice'"},
    {"name": "Cassandra", "meaning": "Greek origin, meaning 'unheeded prophetess'"},
    {"name": "Daphne", "meaning": "Greek origin, meaning 'laurel' or 'bay tree'"},
    {"name": "Electra", "meaning": "Greek origin, meaning 'amber' or 'shining'"},
    {"name": "Eirene", "meaning": "Greek origin, meaning 'peace'"},
    {"name": "Euphemia", "meaning": "Greek origin, meaning 'well-spoken'"},
    {"name": "Galatea", "meaning": "Greek origin, meaning 'milk-white'"},
    {"name": "Hera", "meaning": "Greek origin, name of the queen of the gods"},
    {"name": "Hestia", "meaning": "Greek origin, goddess of the hearth, meaning 'hearth'"},
    {"name": "Io", "meaning": "Greek mythological name, a priestess of Hera"},
    {"name": "Irene", "meaning": "Greek origin, meaning 'peace'"},
    {"name": "Lyra", "meaning": "Greek origin, meaning 'lyre' or 'musical instrument'"},
    {"name": "Medea", "meaning": "Greek origin, meaning 'cunning' or 'to plan'"},
    {"name": "Melisande", "meaning": "Germanic and Greek origin, meaning 'strong in work'"},
    {"name": "Nike", "meaning": "Greek origin, name of the goddess of victory"},
    {"name": "Penelope", "meaning": "Greek origin, meaning 'weaver'"},
    {"name": "Thalia", "meaning": "Greek origin, muse of comedy, meaning 'to bloom'"},
    {"name": "Xanthe", "meaning": "Greek origin, meaning 'yellow' or 'blonde'"},
    {"name": "Zephyrine", "meaning": "Greek origin, feminine of Zephyrus, meaning 'west wind'"},
    {"name": "Anastasia", "meaning": "Greek origin, meaning 'resurrection'"},
    {"name": "Callista", "meaning": "Greek origin, meaning 'most beautiful'"},
    {"name": "Cleopatra", "meaning": "Greek origin, meaning 'glory of her father'"},
    {"name": "Clio", "meaning": "Greek origin, muse of history, meaning 'glory'"},
    {"name": "Dimitra", "meaning": "Greek origin, feminine of Demetrios, meaning 'earth-lover'"},
    {"name": "Georgia", "meaning": "Greek origin, feminine of George, meaning 'farmer'"},
    {"name": "Helena", "meaning": "Greek origin, meaning 'torch' or 'shining light'"},
    {"name": "Katerina", "meaning": "Greek origin, meaning 'pure'"},
    {"name": "Nyx", "meaning": "Greek origin, goddess of the night, meaning 'night'"},
    {"name": "Selene", "meaning": "Greek origin, goddess of the moon, meaning 'moon'"},
    {"name": "Thea", "meaning": "Greek origin, meaning 'goddess' or 'godly'"},
    {"name": "Terpsichore", "meaning": "Greek origin, muse of dance, meaning 'delight in dancing'"},

    # ---- AFRICAN GIRL NAMES ----
    {"name": "Amara", "meaning": "Igbo and African origin, meaning 'grace' or 'eternal'"},
    {"name": "Adaeze", "meaning": "Igbo origin, meaning 'daughter of the king'"},
    {"name": "Adaora", "meaning": "Igbo origin, meaning 'daughter of the community'"},
    {"name": "Afia", "meaning": "Akan origin (Ghana), meaning 'born on Friday'"},
    {"name": "Akosua", "meaning": "Akan origin, meaning 'born on Sunday'"},
    {"name": "Amina", "meaning": "Arabic and Swahili origin, meaning 'honest' or 'trustworthy'"},
    {"name": "Ayana", "meaning": "Ethiopian origin, meaning 'beautiful flower'"},
    {"name": "Chiamaka", "meaning": "Igbo origin, meaning 'God is beautiful'"},
    {"name": "Chidinma", "meaning": "Igbo origin, meaning 'God is good'"},
    {"name": "Chinwe", "meaning": "Igbo origin, meaning 'God owns'"},
    {"name": "Ebele", "meaning": "Igbo origin, meaning 'mercy'"},
    {"name": "Efua", "meaning": "Akan origin, meaning 'born on Friday'"},
    {"name": "Eze", "meaning": "Igbo origin, meaning 'king'"},
    {"name": "Fatoumata", "meaning": "West African form of Fatima, meaning 'captivating'"},
    {"name": "Folake", "meaning": "Yoruba origin, meaning 'be pampered with wealth'"},
    {"name": "Imani", "meaning": "Swahili origin, meaning 'faith'"},
    {"name": "Isha", "meaning": "Swahili origin, meaning 'life'"},
    {"name": "Kadiatou", "meaning": "West African origin, form of Khadija, meaning 'premature child'"},
    {"name": "Kamili", "meaning": "Swahili origin, meaning 'perfect' or 'complete'"},
    {"name": "Kefilwe", "meaning": "Tswana origin, meaning 'I have been given'"},
    {"name": "Kemi", "meaning": "Yoruba origin, short for Oluwakemi, meaning 'God nurtures me'"},
    {"name": "Kumari", "meaning": "Sanskrit and African origin, meaning 'young girl'"},
    {"name": "Lola", "meaning": "Yoruba origin, short for Omolola, meaning 'rich child'"},
    {"name": "Lulu", "meaning": "Swahili origin, meaning 'precious' or 'pearl'"},
    {"name": "Makena", "meaning": "Kikuyu origin (Kenya), meaning 'happy one'"},
    {"name": "Mammie", "meaning": "West African form of Mary, meaning 'beloved'"},
    {"name": "Morwenna", "meaning": "Welsh and Cornish origin, meaning 'maiden'"},
    {"name": "Naledi", "meaning": "Sotho origin, meaning 'star'"},
    {"name": "Nkechi", "meaning": "Igbo origin, meaning 'what God has given me'"},
    {"name": "Nkiruka", "meaning": "Igbo origin, meaning 'the future is greater'"},
    {"name": "Nzinga", "meaning": "Bantu origin, name of a famous Angolan queen"},
    {"name": "Ola", "meaning": "Yoruba origin, meaning 'wealth' or 'honor'"},
    {"name": "Omowunmi", "meaning": "Yoruba origin, meaning 'child brings happiness'"},
    {"name": "Penda", "meaning": "Swahili origin, meaning 'love'"},
    {"name": "Sade", "meaning": "Yoruba origin, meaning 'honor confers a crown'"},
    {"name": "Thandeka", "meaning": "Zulu origin, meaning 'beloved'"},
    {"name": "Titilola", "meaning": "Yoruba origin, meaning 'wealth is eternal'"},
    {"name": "Tolulope", "meaning": "Yoruba origin, meaning 'all belongs to God'"},
    {"name": "Uchenna", "meaning": "Igbo origin, meaning 'God's will'"},
    {"name": "Uzoma", "meaning": "Igbo origin, meaning 'born during a journey'"},
    {"name": "Yetunde", "meaning": "Yoruba origin, meaning 'mother has returned'"},
    {"name": "Zola", "meaning": "Zulu origin, meaning 'calm' or 'tranquil'"},

    # ---- SANSKRIT / INDIAN GIRL NAMES ----
    {"name": "Priya", "meaning": "Sanskrit origin, meaning 'beloved' or 'dear'"},
    {"name": "Ananya", "meaning": "Sanskrit origin, meaning 'unique' or 'incomparable'"},
    {"name": "Anika", "meaning": "Sanskrit and Swahili origin, meaning 'grace' or 'army'"},
    {"name": "Anjali", "meaning": "Sanskrit origin, meaning 'offering' or 'gift'"},
    {"name": "Anushka", "meaning": "Sanskrit origin, meaning 'grace' or 'favor'"},
    {"name": "Bhumi", "meaning": "Sanskrit origin, meaning 'earth'"},
    {"name": "Chitra", "meaning": "Sanskrit origin, meaning 'picture' or 'painting'"},
    {"name": "Deepa", "meaning": "Sanskrit origin, meaning 'light' or 'lamp'"},
    {"name": "Devika", "meaning": "Sanskrit origin, meaning 'little goddess'"},
    {"name": "Diya", "meaning": "Sanskrit and Arabic origin, meaning 'light' or 'lamp'"},
    {"name": "Durga", "meaning": "Sanskrit origin, name of the Hindu warrior goddess"},
    {"name": "Gita", "meaning": "Sanskrit origin, meaning 'song' or 'divine song'"},
    {"name": "Hema", "meaning": "Sanskrit origin, meaning 'golden'"},
    {"name": "Indu", "meaning": "Sanskrit origin, meaning 'moon'"},
    {"name": "Jaya", "meaning": "Sanskrit origin, meaning 'victory'"},
    {"name": "Jayashree", "meaning": "Sanskrit origin, meaning 'goddess of victory'"},
    {"name": "Kamala", "meaning": "Sanskrit origin, meaning 'lotus' or 'pale red'"},
    {"name": "Kavya", "meaning": "Sanskrit origin, meaning 'poem' or 'poetry'"},
    {"name": "Lalita", "meaning": "Sanskrit origin, meaning 'playful' or 'charming'"},
    {"name": "Lakshmi", "meaning": "Sanskrit origin, name of the goddess of wealth"},
    {"name": "Madhuri", "meaning": "Sanskrit origin, meaning 'sweet' or 'nectar'"},
    {"name": "Malini", "meaning": "Sanskrit origin, meaning 'fragrant' or 'gardener'"},
    {"name": "Mansi", "meaning": "Sanskrit origin, meaning 'woman' or 'mind'"},
    {"name": "Meera", "meaning": "Sanskrit origin, meaning 'sea' or 'prosperous'"},
    {"name": "Mithila", "meaning": "Sanskrit origin, meaning 'from the land of Mithila'"},
    {"name": "Mrinalini", "meaning": "Sanskrit origin, meaning 'lotus stem'"},
    {"name": "Nandini", "meaning": "Sanskrit origin, meaning 'daughter' or 'delightful'"},
    {"name": "Neha", "meaning": "Sanskrit origin, meaning 'love' or 'rain'"},
    {"name": "Nisha", "meaning": "Sanskrit origin, meaning 'night'"},
    {"name": "Nita", "meaning": "Sanskrit origin, meaning 'well-behaved' or 'moral'"},
    {"name": "Padma", "meaning": "Sanskrit origin, meaning 'lotus flower'"},
    {"name": "Parvati", "meaning": "Sanskrit origin, name of the Hindu goddess of love"},
    {"name": "Pooja", "meaning": "Sanskrit origin, meaning 'worship' or 'prayer'"},
    {"name": "Radha", "meaning": "Sanskrit origin, meaning 'prosperity' or 'beloved'"},
    {"name": "Ritu", "meaning": "Sanskrit origin, meaning 'season'"},
    {"name": "Rohini", "meaning": "Sanskrit origin, meaning 'red cow' or 'ascending'"},
    {"name": "Rukmini", "meaning": "Sanskrit origin, name of Krishna's principal wife"},
    {"name": "Saraswati", "meaning": "Sanskrit origin, name of the goddess of knowledge"},
    {"name": "Savita", "meaning": "Sanskrit origin, meaning 'sun' or 'animator'"},
    {"name": "Seema", "meaning": "Sanskrit origin, meaning 'boundary' or 'limit'"},
    {"name": "Shanti", "meaning": "Sanskrit origin, meaning 'peace' or 'tranquility'"},
    {"name": "Sheetal", "meaning": "Sanskrit origin, meaning 'cool' or 'calm'"},
    {"name": "Shruti", "meaning": "Sanskrit origin, meaning 'heard' or 'sacred text'"},
    {"name": "Sudha", "meaning": "Sanskrit origin, meaning 'nectar' or 'ambrosia'"},
    {"name": "Sunita", "meaning": "Sanskrit origin, meaning 'well-guided'"},
    {"name": "Sushma", "meaning": "Sanskrit origin, meaning 'beautiful'"},
    {"name": "Swati", "meaning": "Sanskrit origin, meaning 'a star' or 'good'"},
    {"name": "Usha", "meaning": "Sanskrit origin, name of the dawn goddess"},
    {"name": "Vandana", "meaning": "Sanskrit origin, meaning 'worship' or 'salutation'"},
    {"name": "Vani", "meaning": "Sanskrit origin, meaning 'voice' or 'speech'"},
    {"name": "Vidya", "meaning": "Sanskrit origin, meaning 'knowledge' or 'wisdom'"},
    {"name": "Yamuna", "meaning": "Sanskrit origin, name of the sacred river in India"},

    # ---- JAPANESE GIRL NAMES ----
    {"name": "Hana", "meaning": "Japanese origin, meaning 'flower'"},
    {"name": "Sakura", "meaning": "Japanese origin, meaning 'cherry blossom'"},
    {"name": "Yuki", "meaning": "Japanese origin, meaning 'snow' or 'happiness'"},
    {"name": "Aiko", "meaning": "Japanese origin, meaning 'beloved child'"},
    {"name": "Akemi", "meaning": "Japanese origin, meaning 'bright' and 'beautiful'"},
    {"name": "Ami", "meaning": "Japanese origin, meaning 'second beauty'"},
    {"name": "Aya", "meaning": "Japanese origin, meaning 'colorful' or 'design'"},
    {"name": "Chika", "meaning": "Japanese origin, meaning 'near' or 'scattered flowers'"},
    {"name": "Chiyo", "meaning": "Japanese origin, meaning 'thousand generations'"},
    {"name": "Emi", "meaning": "Japanese origin, meaning 'blessed with beauty'"},
    {"name": "Emiko", "meaning": "Japanese origin, meaning 'prosperous' and 'beautiful child'"},
    {"name": "Fumi", "meaning": "Japanese origin, meaning 'history' or 'sentence'"},
    {"name": "Hanako", "meaning": "Japanese origin, meaning 'flower child'"},
    {"name": "Haruka", "meaning": "Japanese origin, meaning 'spring flower' or 'distant'"},
    {"name": "Hikari", "meaning": "Japanese origin, meaning 'light' or 'radiance'"},
    {"name": "Himari", "meaning": "Japanese origin, meaning 'sunflower'"},
    {"name": "Hinata", "meaning": "Japanese origin, meaning 'sunny place' or 'facing the sun'"},
    {"name": "Hotaru", "meaning": "Japanese origin, meaning 'firefly'"},
    {"name": "Hoshi", "meaning": "Japanese origin, meaning 'star'"},
    {"name": "Izumi", "meaning": "Japanese origin, meaning 'spring' or 'fountain'"},
    {"name": "Kaede", "meaning": "Japanese origin, meaning 'maple tree'"},
    {"name": "Kagome", "meaning": "Japanese origin, meaning 'woven bamboo pattern'"},
    {"name": "Kanako", "meaning": "Japanese origin, meaning 'fragrance child'"},
    {"name": "Kanna", "meaning": "Japanese origin, meaning 'summer waves'"},
    {"name": "Kaori", "meaning": "Japanese origin, meaning 'fragrance' or 'scent'"},
    {"name": "Kasumi", "meaning": "Japanese origin, meaning 'mist' or 'haze'"},
    {"name": "Kiyomi", "meaning": "Japanese origin, meaning 'pure beauty'"},
    {"name": "Koharu", "meaning": "Japanese origin, meaning 'small spring'"},
    {"name": "Kotone", "meaning": "Japanese origin, meaning 'sound of the koto'"},
    {"name": "Kumiko", "meaning": "Japanese origin, meaning 'long-time beautiful child'"},
    {"name": "Kumi", "meaning": "Japanese origin, meaning 'braid'"},
    {"name": "Kyoko", "meaning": "Japanese origin, meaning 'mirror' or 'capital'"},
    {"name": "Mahiru", "meaning": "Japanese origin, meaning 'noon' or 'broad daylight'"},
    {"name": "Maki", "meaning": "Japanese origin, meaning 'true hope'"},
    {"name": "Mana", "meaning": "Japanese origin, meaning 'love' or 'affection'"},
    {"name": "Manami", "meaning": "Japanese origin, meaning 'love' and 'beautiful sea'"},
    {"name": "Mayu", "meaning": "Japanese origin, meaning 'true' and 'gentle'"},
    {"name": "Midori", "meaning": "Japanese origin, meaning 'green'"},
    {"name": "Miharu", "meaning": "Japanese origin, meaning 'beautiful' and 'spring'"},
    {"name": "Miku", "meaning": "Japanese origin, meaning 'beautiful sky'"},
    {"name": "Minami", "meaning": "Japanese origin, meaning 'south'"},
    {"name": "Misaki", "meaning": "Japanese origin, meaning 'beautiful blossom'"},
    {"name": "Miyu", "meaning": "Japanese origin, meaning 'beautiful' and 'gentle'"},
    {"name": "Miyuki", "meaning": "Japanese origin, meaning 'deep snow'"},
    {"name": "Momoko", "meaning": "Japanese origin, meaning 'peach child'"},
    {"name": "Nami", "meaning": "Japanese origin, meaning 'wave'"},
    {"name": "Nanami", "meaning": "Japanese origin, meaning 'seven seas'"},
    {"name": "Naomi", "meaning": "Japanese and Hebrew origin, meaning 'straight' or 'honest'"},
    {"name": "Natsumi", "meaning": "Japanese origin, meaning 'summer beauty'"},
    {"name": "Nozomi", "meaning": "Japanese origin, meaning 'wish' or 'hope'"},
    {"name": "Rei", "meaning": "Japanese origin, meaning 'beautiful' or 'bell'"},
    {"name": "Rena", "meaning": "Japanese origin, meaning 'lovely' or 'peaceful'"},
    {"name": "Rin", "meaning": "Japanese origin, meaning 'dignified'"},
    {"name": "Risa", "meaning": "Japanese origin, meaning 'village' and 'apple'"},
    {"name": "Ryoko", "meaning": "Japanese origin, meaning 'refreshing child'"},
    {"name": "Saki", "meaning": "Japanese origin, meaning 'blossom hope'"},
    {"name": "Sana", "meaning": "Japanese origin, meaning 'sand' or 'honest'"},
    {"name": "Satomi", "meaning": "Japanese origin, meaning 'wise' and 'beautiful'"},
    {"name": "Satsuki", "meaning": "Japanese origin, meaning 'the month of May'"},
    {"name": "Sayuri", "meaning": "Japanese origin, meaning 'small lily'"},
    {"name": "Sena", "meaning": "Japanese origin, meaning 'brilliant' and 'Nara'"},
    {"name": "Shiori", "meaning": "Japanese origin, meaning 'poem' or 'bookmark'"},
    {"name": "Shizuka", "meaning": "Japanese origin, meaning 'quiet' or 'gentle'"},
    {"name": "Sora", "meaning": "Japanese origin, meaning 'sky'"},
    {"name": "Sumire", "meaning": "Japanese origin, meaning 'violet flower'"},
    {"name": "Tsubaki", "meaning": "Japanese origin, meaning 'camellia flower'"},
    {"name": "Tsuki", "meaning": "Japanese origin, meaning 'moon'"},
    {"name": "Yui", "meaning": "Japanese origin, meaning 'bind' or 'tie together'"},
    {"name": "Yumi", "meaning": "Japanese origin, meaning 'reason' and 'beauty'"},
    {"name": "Yuna", "meaning": "Japanese origin, meaning 'gentle' or 'superior'"},
    {"name": "Yuri", "meaning": "Japanese origin, meaning 'lily'"},

    # ---- NATURE GIRL NAMES ----
    {"name": "Blossom", "meaning": "Old English nature name referring to blooming flowers"},
    {"name": "Clover", "meaning": "Old English nature name referring to the clover plant"},
    {"name": "Coral", "meaning": "Latin origin, from the sea coral organism"},
    {"name": "Crystal", "meaning": "Greek origin, meaning 'clear ice' or 'sparkling'"},
    {"name": "Dawn", "meaning": "Old English nature name meaning 'daybreak'"},
    {"name": "Fern", "meaning": "Old English nature name referring to the fern plant"},
    {"name": "Flora", "meaning": "Latin origin, name of the goddess of flowers"},
    {"name": "Florentina", "meaning": "Latin origin, meaning 'flowering' or 'blossoming'"},
    {"name": "Forest", "meaning": "Old English nature name meaning 'of the forest'"},
    {"name": "Gem", "meaning": "Latin origin, meaning 'precious stone'"},
    {"name": "Glade", "meaning": "Old English nature name meaning 'open space in a forest'"},
    {"name": "Heather", "meaning": "Old English nature name referring to the heather plant"},
    {"name": "Holly", "meaning": "Old English nature name referring to the holly tree"},
    {"name": "Iris", "meaning": "Greek origin, meaning 'rainbow' or 'iris flower'"},
    {"name": "Ivy", "meaning": "Old English nature name referring to the climbing ivy plant"},
    {"name": "Juniper", "meaning": "Latin origin, from the juniper tree"},
    {"name": "Lavender", "meaning": "Latin origin, from the lavender plant"},
    {"name": "Lilac", "meaning": "Persian origin, from the lilac flower"},
    {"name": "Lotus", "meaning": "Greek origin, from the lotus flower"},
    {"name": "Magnolia", "meaning": "French origin, from the magnolia tree"},
    {"name": "Maple", "meaning": "Old English nature name referring to the maple tree"},
    {"name": "Marigold", "meaning": "Old English nature name, combination of Mary and gold"},
    {"name": "Meadow", "meaning": "Old English nature name referring to a field of grass"},
    {"name": "Misty", "meaning": "Old English nature name meaning 'covered in mist'"},
    {"name": "Moss", "meaning": "Old English nature name referring to the moss plant"},
    {"name": "Opal", "meaning": "Sanskrit origin, from the gemstone meaning 'precious stone'"},
    {"name": "Pansy", "meaning": "Old French nature name from the pansy flower"},
    {"name": "Pearl", "meaning": "Latin origin, from the pearl gemstone"},
    {"name": "Petal", "meaning": "Greek origin, meaning 'leaf' of a flower"},
    {"name": "Posy", "meaning": "Old English origin, meaning 'small bouquet of flowers'"},
    {"name": "Primrose", "meaning": "Latin origin, meaning 'first rose'"},
    {"name": "Rain", "meaning": "Old English nature name referring to rainfall"},
    {"name": "Rainbow", "meaning": "Old English nature name referring to the rainbow"},
    {"name": "Rosemary", "meaning": "Latin origin, from the rosemary herb"},
    {"name": "Sandy", "meaning": "Old English origin, meaning 'sandy place'"},
    {"name": "Skye", "meaning": "Old Norse origin, from the Isle of Skye, meaning 'sky'"},
    {"name": "Spring", "meaning": "Old English nature name referring to the spring season"},
    {"name": "Summer", "meaning": "Old English nature name referring to the summer season"},
    {"name": "Sunny", "meaning": "Old English nature name meaning 'bright like the sun'"},
    {"name": "Tempest", "meaning": "Old French nature name meaning 'storm'"},
    {"name": "Terra", "meaning": "Latin origin, meaning 'earth' or 'land'"},
    {"name": "Wren", "meaning": "Old English nature name referring to the small songbird"},
    {"name": "Yarrow", "meaning": "Old English nature name from the yarrow herb"},
    {"name": "Zinnia", "meaning": "Latin origin, from the zinnia flower"},

    # ---- VINTAGE / OLD-FASHIONED GIRL NAMES ----
    {"name": "Mabel", "meaning": "Latin origin, meaning 'lovable' or 'dear'"},
    {"name": "Cordelia", "meaning": "Latin and Celtic origin, meaning 'heart' or 'daughter of the sea'"},
    {"name": "Gertrude", "meaning": "Old Germanic origin, meaning 'strength of a spear'"},
    {"name": "Harriet", "meaning": "Old Germanic origin, feminine of Harry, meaning 'home ruler'"},
    {"name": "Hortense", "meaning": "Latin origin, meaning 'garden'"},
    {"name": "Ida", "meaning": "Old Germanic origin, meaning 'hardworking'"},
    {"name": "Imogen", "meaning": "Celtic origin, possibly meaning 'maiden'"},
    {"name": "Mildred", "meaning": "Old English origin, meaning 'gentle strength'"},
    {"name": "Millicent", "meaning": "Old Germanic origin, meaning 'strong in work'"},
    {"name": "Minerva", "meaning": "Latin origin, name of the Roman goddess of wisdom"},
    {"name": "Mirabel", "meaning": "Latin origin, meaning 'wonderful'"},
    {"name": "Myrtis", "meaning": "Greek origin, from the myrtle plant"},
    {"name": "Nella", "meaning": "Italian origin, short for Antonella, meaning 'priceless'"},
    {"name": "Olive", "meaning": "Latin origin, from the olive tree symbolizing peace"},
    {"name": "Opal", "meaning": "Sanskrit origin, from the gemstone meaning 'precious'"},
    {"name": "Ottilie", "meaning": "Old Germanic origin, meaning 'prosperity'"},
    {"name": "Phoebe", "meaning": "Greek origin, meaning 'bright' or 'pure'"},
    {"name": "Theodora", "meaning": "Greek origin, meaning 'gift of God'"},
    {"name": "Vera", "meaning": "Latin and Slavic origin, meaning 'truth' or 'faith'"},
    {"name": "Winifred", "meaning": "Old Welsh origin, meaning 'blessed' and 'peaceful'"},
    {"name": "Adela", "meaning": "Old Germanic origin, meaning 'noble'"},
    {"name": "Agatha", "meaning": "Greek origin, meaning 'good' or 'virtuous'"},
    {"name": "Agnes", "meaning": "Greek origin, meaning 'pure' or 'holy'"},
    {"name": "Albina", "meaning": "Latin origin, meaning 'white' or 'fair'"},
    {"name": "Aldora", "meaning": "Greek origin, meaning 'winged gift'"},
    {"name": "Alethea", "meaning": "Greek origin, meaning 'truth'"},
    {"name": "Almeria", "meaning": "Arabic origin, meaning 'princess of the amir'"},
    {"name": "Althea", "meaning": "Greek origin, meaning 'with healing power'"},
    {"name": "Alvina", "meaning": "Old Germanic origin, meaning 'noble friend'"},
    {"name": "Arabella", "meaning": "Latin origin, meaning 'yielding to prayer'"},
    {"name": "Araminta", "meaning": "Hebrew origin, possibly meaning 'lofty'"},
    {"name": "Ardith", "meaning": "Hebrew origin, meaning 'flowering field'"},
    {"name": "Ariel", "meaning": "Hebrew origin, meaning 'lion of God'"},
    {"name": "Arline", "meaning": "Celtic origin, meaning 'pledge'"},
    {"name": "Armilla", "meaning": "Latin origin, meaning 'bracelet'"},
    {"name": "Arnolda", "meaning": "Old Germanic origin, meaning 'eagle power'"},
    {"name": "Artemis", "meaning": "Greek origin, goddess of the hunt, meaning 'butcher'"},
    {"name": "Arvilla", "meaning": "Old German origin, meaning 'eagle village'"},
    {"name": "Attie", "meaning": "Latin origin, short for Attilia, meaning 'from Attica'"},
    {"name": "Audra", "meaning": "Lithuanian and English origin, meaning 'storm'"},
    {"name": "Augie", "meaning": "Latin origin, short for Augusta, meaning 'great'"},
    {"name": "Augusta", "meaning": "Latin origin, meaning 'great' or 'venerable'"},
    {"name": "Augustina", "meaning": "Latin origin, feminine of Augustus, meaning 'great'"},
    {"name": "Aurore", "meaning": "French form of Aurora, meaning 'dawn'"},
    {"name": "Avis", "meaning": "Latin origin, meaning 'bird'"},
    {"name": "Azalea", "meaning": "Greek origin, from the azalea flower, meaning 'dry'"},
    {"name": "Bea", "meaning": "Latin origin, short for Beatrice, meaning 'bringer of joy'"},
    {"name": "Beatrice", "meaning": "Latin origin, meaning 'bringer of joy' or 'blessed'"},
    {"name": "Beatrix", "meaning": "Latin origin, meaning 'bringer of joy'"},
    {"name": "Beda", "meaning": "Old English origin, meaning 'battle maiden'"},
    {"name": "Bedelia", "meaning": "Irish form of Bridget, meaning 'exalted one'"},
    {"name": "Belinda", "meaning": "Old Germanic origin, meaning 'bright serpent'"},
    {"name": "Belle", "meaning": "French origin, meaning 'beautiful'"},
    {"name": "Bernadette", "meaning": "French form of Bernard, meaning 'brave bear'"},
    {"name": "Bernice", "meaning": "Greek origin, meaning 'bringing victory'"},
    {"name": "Bertha", "meaning": "Old Germanic origin, meaning 'bright' or 'famous'"},
    {"name": "Bertina", "meaning": "Old Germanic origin, meaning 'bright'"},
    {"name": "Bessie", "meaning": "Hebrew origin, diminutive of Elizabeth"},
    {"name": "Blanche", "meaning": "French origin, meaning 'white' or 'fair'"},
    {"name": "Brigitte", "meaning": "French form of Bridget, meaning 'exalted one'"},
    {"name": "Brunhilde", "meaning": "Old Germanic origin, meaning 'armored battle maiden'"},
    {"name": "Calista", "meaning": "Greek origin, meaning 'most beautiful'"},
    {"name": "Camille", "meaning": "Latin origin, meaning 'ceremonial attendant'"},
    {"name": "Carlotta", "meaning": "Italian form of Charlotte, meaning 'free woman'"},
    {"name": "Carmel", "meaning": "Hebrew origin, meaning 'garden' or 'vineyard'"},
    {"name": "Cecilia", "meaning": "Latin origin, meaning 'blind' or 'of the Caecilii family'"},
    {"name": "Celestine", "meaning": "Latin origin, meaning 'heavenly'"},
    {"name": "Celeste", "meaning": "Latin origin, meaning 'heavenly'"},
    {"name": "Clementine", "meaning": "Latin origin, meaning 'gentle' or 'merciful'"},
    {"name": "Clotilde", "meaning": "Old Germanic origin, meaning 'famous battle'"},
    {"name": "Constance", "meaning": "Latin origin, meaning 'constant' or 'steadfast'"},
    {"name": "Cornelia", "meaning": "Latin origin, feminine of Cornelius"},
    {"name": "Cressida", "meaning": "Greek origin, meaning 'gold'"},
    {"name": "Dagmar", "meaning": "Old Norse origin, meaning 'day' and 'maid'"},
    {"name": "Damaris", "meaning": "Greek origin, meaning 'gentle'"},
    {"name": "Davina", "meaning": "Hebrew origin, feminine of David, meaning 'beloved'"},
    {"name": "Delia", "meaning": "Greek origin, meaning 'from Delos'"},
    {"name": "Della", "meaning": "Old Germanic origin, short for Adela, meaning 'noble'"},
    {"name": "Dolores", "meaning": "Spanish origin, meaning 'sorrows'"},
    {"name": "Dorothea", "meaning": "Greek origin, meaning 'gift of God'"},
    {"name": "Dulcie", "meaning": "Latin origin, meaning 'sweet'"},
    {"name": "Edith", "meaning": "Old English origin, meaning 'prosperous in war'"},
    {"name": "Edwina", "meaning": "Old English origin, meaning 'wealthy friend'"},
    {"name": "Effie", "meaning": "Greek origin, short for Euphemia, meaning 'well-spoken'"},
    {"name": "Eliza", "meaning": "Hebrew origin, short form of Elizabeth, meaning 'God's oath'"},
    {"name": "Elspeth", "meaning": "Scottish form of Elizabeth, meaning 'God's oath'"},
    {"name": "Emmeline", "meaning": "Old Germanic origin, meaning 'whole' or 'universal'"},
    {"name": "Enid", "meaning": "Welsh origin, meaning 'life' or 'spirit'"},
    {"name": "Eudora", "meaning": "Greek origin, meaning 'good gift'"},
    {"name": "Eugenia", "meaning": "Greek origin, meaning 'well-born' or 'noble'"},
    {"name": "Eulalia", "meaning": "Greek origin, meaning 'sweetly spoken'"},
    {"name": "Eustacia", "meaning": "Greek origin, meaning 'fruitful'"},
    {"name": "Evangeline", "meaning": "Greek origin, meaning 'bearer of good news'"},
    {"name": "Eveline", "meaning": "French form of Evelyn, meaning 'wished for child'"},
    {"name": "Felicity", "meaning": "Latin origin, meaning 'happiness' or 'good fortune'"},
    {"name": "Fenella", "meaning": "Scottish Gaelic origin, meaning 'white shoulder'"},
    {"name": "Fidelia", "meaning": "Latin origin, meaning 'faithful'"},
    {"name": "Filippa", "meaning": "Italian and Scandinavian form of Philippa, meaning 'horse lover'"},
    {"name": "Fleur", "meaning": "French origin, meaning 'flower'"},
    {"name": "Florentine", "meaning": "Latin origin, meaning 'flowering' or 'blossoming'"},
    {"name": "Florinda", "meaning": "Spanish and Portuguese origin, meaning 'flowering'"},
    {"name": "Frederica", "meaning": "Old Germanic origin, meaning 'peaceful ruler'"},

    # ---- SPANISH / LATIN AMERICAN GIRL NAMES ----
    {"name": "Adriana", "meaning": "Latin origin, meaning 'from Hadria'"},
    {"name": "Alejandra", "meaning": "Spanish form of Alexandra, meaning 'defender of men'"},
    {"name": "Alicia", "meaning": "Spanish form of Alice, meaning 'noble'"},
    {"name": "Alondra", "meaning": "Spanish origin, meaning 'lark bird'"},
    {"name": "Amparo", "meaning": "Spanish origin, meaning 'protection' or 'shelter'"},
    {"name": "Ana", "meaning": "Spanish and Portuguese form of Anna, meaning 'grace'"},
    {"name": "Belen", "meaning": "Spanish origin, from the town of Bethlehem"},
    {"name": "Camila", "meaning": "Spanish form of Camille, meaning 'ceremonial attendant'"},
    {"name": "Carmen", "meaning": "Spanish origin, meaning 'garden' or 'orchard'"},
    {"name": "Concepcion", "meaning": "Spanish origin, meaning 'conception' or 'immaculate'"},
    {"name": "Consuelo", "meaning": "Spanish origin, meaning 'consolation'"},
    {"name": "Dolores", "meaning": "Spanish origin, meaning 'sorrows'"},
    {"name": "Elena", "meaning": "Spanish and Italian form of Helen, meaning 'shining light'"},
    {"name": "Fernanda", "meaning": "Spanish form of Ferdinanda, meaning 'bold voyager'"},
    {"name": "Guadalupe", "meaning": "Spanish origin, meaning 'valley of wolves'"},
    {"name": "Inés", "meaning": "Spanish form of Agnes, meaning 'pure'"},
    {"name": "Isabella", "meaning": "Spanish form of Elizabeth, meaning 'God is my oath'"},
    {"name": "Lucia", "meaning": "Spanish and Italian form of Lucy, meaning 'light'"},
    {"name": "Lupe", "meaning": "Spanish short form of Guadalupe, meaning 'wolf valley'"},
    {"name": "Marisol", "meaning": "Spanish combination of Maria and Sol, meaning 'sea and sun'"},
    {"name": "Mercedes", "meaning": "Spanish origin, meaning 'mercies'"},
    {"name": "Milagros", "meaning": "Spanish origin, meaning 'miracles'"},
    {"name": "Monica", "meaning": "Latin origin, possibly meaning 'advisor'"},
    {"name": "Paloma", "meaning": "Spanish origin, meaning 'dove'"},
    {"name": "Pilar", "meaning": "Spanish origin, meaning 'pillar'"},
    {"name": "Remedios", "meaning": "Spanish origin, meaning 'remedies'"},
    {"name": "Rosario", "meaning": "Spanish origin, meaning 'rosary'"},
    {"name": "Soledad", "meaning": "Spanish origin, meaning 'solitude'"},
    {"name": "Verónica", "meaning": "Latin origin, meaning 'true image'"},
    {"name": "Xiomara", "meaning": "Spanish form of Geumar, meaning 'famous warrior'"},
    {"name": "Ximena", "meaning": "Spanish form of Simona, meaning 'one who hears'"},
    {"name": "Yolanda", "meaning": "Greek origin via Spanish, meaning 'violet flower'"},
    {"name": "Zita", "meaning": "Italian origin, meaning 'little girl'"},
    {"name": "Emilia", "meaning": "Latin origin, meaning 'rival' or 'excel'"},
    {"name": "Florencia", "meaning": "Spanish form of Florence, meaning 'flourishing'"},
    {"name": "Gabriela", "meaning": "Hebrew origin via Spanish, meaning 'God is my strength'"},
    {"name": "Esperanza", "meaning": "Spanish origin, meaning 'hope'"},

    # ---- FRENCH GIRL NAMES ----
    {"name": "Adele", "meaning": "Old Germanic origin, meaning 'noble'"},
    {"name": "Amelie", "meaning": "French form of Amelia, meaning 'hardworking'"},
    {"name": "Brigitte", "meaning": "French form of Bridget, meaning 'exalted one'"},
    {"name": "Cecile", "meaning": "French form of Cecilia, meaning 'blind'"},
    {"name": "Chantal", "meaning": "French origin, meaning 'stony place'"},
    {"name": "Colette", "meaning": "French form of Nicolette, meaning 'victory of the people'"},
    {"name": "Cosette", "meaning": "French origin, meaning 'little thing'"},
    {"name": "Eloise", "meaning": "Old French origin, meaning 'famous warrior'"},
    {"name": "Genevieve", "meaning": "Germanic origin via French, meaning 'woman of the people'"},
    {"name": "Giselle", "meaning": "Old Germanic origin, meaning 'pledge'"},
    {"name": "Heloise", "meaning": "Old French origin, meaning 'famous warrior'"},
    {"name": "Isabelle", "meaning": "French form of Isabel, meaning 'God is my oath'"},
    {"name": "Josephine", "meaning": "Hebrew origin via French, meaning 'God will add'"},
    {"name": "Juliette", "meaning": "French form of Julia, meaning 'youthful'"},
    {"name": "Lisette", "meaning": "French diminutive of Elizabeth, meaning 'God's oath'"},
    {"name": "Lucille", "meaning": "French form of Lucilla, meaning 'light'"},
    {"name": "Madeleine", "meaning": "French form of Magdalene, meaning 'woman of Magdala'"},
    {"name": "Margot", "meaning": "French form of Margaret, meaning 'pearl'"},
    {"name": "Marie", "meaning": "French form of Mary, meaning 'beloved'"},
    {"name": "Marion", "meaning": "French form of Mary, meaning 'beloved'"},
    {"name": "Monique", "meaning": "French form of Monica, meaning 'advisor'"},
    {"name": "Nadine", "meaning": "French form of Nadia, meaning 'hope'"},
    {"name": "Nicole", "meaning": "French form of Nicola, meaning 'victory of the people'"},
    {"name": "Odette", "meaning": "French form of Oda, meaning 'wealth'"},
    {"name": "Renee", "meaning": "French form of Renata, meaning 'born again'"},
    {"name": "Simone", "meaning": "French form of Simona, meaning 'one who hears'"},
    {"name": "Sylvie", "meaning": "French form of Silvia, meaning 'forest'"},
    {"name": "Veronique", "meaning": "French form of Veronica, meaning 'true image'"},
    {"name": "Vivienne", "meaning": "French form of Vivian, meaning 'alive' or 'lively'"},
    {"name": "Yvette", "meaning": "French form of Yvonne, meaning 'yew tree'"},
    {"name": "Yvonne", "meaning": "Old Germanic origin via French, meaning 'yew tree'"},
    {"name": "Zoe", "meaning": "Greek origin via French, meaning 'life'"},

    # ---- SLAVIC GIRL NAMES ----
    {"name": "Alena", "meaning": "Slavic form of Helen, meaning 'shining light'"},
    {"name": "Anastasia", "meaning": "Greek origin, meaning 'resurrection'"},
    {"name": "Darya", "meaning": "Persian origin via Russian, meaning 'sea'"},
    {"name": "Galina", "meaning": "Russian origin, meaning 'calm' or 'serene'"},
    {"name": "Irina", "meaning": "Russian form of Irene, meaning 'peace'"},
    {"name": "Katya", "meaning": "Russian diminutive of Ekaterina, meaning 'pure'"},
    {"name": "Lada", "meaning": "Slavic origin, name of the Slavic goddess of beauty"},
    {"name": "Larisa", "meaning": "Russian origin, meaning 'citadel'"},
    {"name": "Liliya", "meaning": "Russian form of Lily, meaning 'lily flower'"},
    {"name": "Ludmila", "meaning": "Slavic origin, meaning 'gracious people'"},
    {"name": "Masha", "meaning": "Russian diminutive of Maria, meaning 'beloved'"},
    {"name": "Natasha", "meaning": "Russian form of Natalia, meaning 'born at Christmas'"},
    {"name": "Natalya", "meaning": "Russian form of Natalia, meaning 'born at Christmas'"},
    {"name": "Nadezhda", "meaning": "Russian origin, meaning 'hope'"},
    {"name": "Nina", "meaning": "Russian and Georgian origin, possibly meaning 'grace'"},
    {"name": "Olga", "meaning": "Old Norse origin via Russian, meaning 'holy'"},
    {"name": "Polina", "meaning": "Russian form of Paulina, meaning 'small'"},
    {"name": "Sasha", "meaning": "Russian short form of Alexandra, meaning 'defender'"},
    {"name": "Sonya", "meaning": "Russian form of Sophia, meaning 'wisdom'"},
    {"name": "Svetlana", "meaning": "Slavic origin, meaning 'light' or 'luminous'"},
    {"name": "Tatiana", "meaning": "Latin origin via Russian, meaning 'fairy queen'"},
    {"name": "Varvara", "meaning": "Russian form of Barbara, meaning 'foreign woman'"},
    {"name": "Veronika", "meaning": "Slavic form of Veronica, meaning 'true image'"},
    {"name": "Vladislava", "meaning": "Slavic origin, meaning 'glorious rule'"},
    {"name": "Zoya", "meaning": "Greek origin via Russian, meaning 'life'"},
    {"name": "Milena", "meaning": "Slavic origin, meaning 'gracious' or 'dear'"},
    {"name": "Monika", "meaning": "German and Slavic form of Monica, meaning 'advisor'"},
    {"name": "Petra", "meaning": "Greek origin via Slavic, meaning 'rock'"},

    # ---- PERSIAN / TURKISH GIRL NAMES ----
    {"name": "Ayla", "meaning": "Turkish and Hebrew origin, meaning 'moonlight' or 'oak tree'"},
    {"name": "Bahar", "meaning": "Persian and Turkish origin, meaning 'spring'"},
    {"name": "Banu", "meaning": "Persian origin, meaning 'lady' or 'princess'"},
    {"name": "Ceren", "meaning": "Turkish origin, meaning 'young gazelle'"},
    {"name": "Dilnoza", "meaning": "Persian origin, meaning 'that which pleases the heart'"},
    {"name": "Elham", "meaning": "Persian and Arabic origin, meaning 'inspiration'"},
    {"name": "Elmira", "meaning": "Persian origin, meaning 'princess of the world'"},
    {"name": "Farida", "meaning": "Arabic and Persian origin, meaning 'unique' or 'precious'"},
    {"name": "Fatma", "meaning": "Turkish form of Fatima, meaning 'captivating'"},
    {"name": "Gulsah", "meaning": "Turkish and Persian origin, meaning 'rose king'"},
    {"name": "Halide", "meaning": "Turkish origin, meaning 'immortal'"},
    {"name": "Kubra", "meaning": "Turkish and Arabic origin, meaning 'greatest'"},
    {"name": "Laleh", "meaning": "Persian origin, meaning 'tulip'"},
    {"name": "Maryam", "meaning": "Persian and Arabic form of Mary, meaning 'beloved'"},
    {"name": "Meltem", "meaning": "Turkish origin, meaning 'sea breeze'"},
    {"name": "Naz", "meaning": "Persian and Turkish origin, meaning 'coquettish' or 'grace'"},
    {"name": "Negar", "meaning": "Persian origin, meaning 'sweetheart' or 'idol'"},
    {"name": "Nilufer", "meaning": "Persian origin, meaning 'lotus flower'"},
    {"name": "Parisa", "meaning": "Persian origin, meaning 'like a fairy'"},
    {"name": "Reyhan", "meaning": "Turkish and Arabic origin, meaning 'basil' or 'sweet basil'"},
    {"name": "Rojda", "meaning": "Kurdish origin, meaning 'dawn'"},
    {"name": "Selin", "meaning": "Turkish origin, meaning 'flooding river'"},
    {"name": "Shirin", "meaning": "Persian origin, meaning 'sweet' or 'pleasant'"},
    {"name": "Yasemin", "meaning": "Turkish form of Jasmine, meaning 'jasmine flower'"},
    {"name": "Zeynep", "meaning": "Turkish form of Zainab, meaning 'fragrant flowering plant'"},

    # ---- CHINESE / KOREAN GIRL NAMES ----
    {"name": "Mei", "meaning": "Chinese origin, meaning 'beautiful' or 'plum'"},
    {"name": "Lan", "meaning": "Chinese and Vietnamese origin, meaning 'orchid' or 'mountain'"},
    {"name": "Ling", "meaning": "Chinese origin, meaning 'spirit' or 'delicate'"},
    {"name": "Xiu", "meaning": "Chinese origin, meaning 'elegant' or 'beautiful'"},
    {"name": "Zhen", "meaning": "Chinese origin, meaning 'precious' or 'rare'"},
    {"name": "Jing", "meaning": "Chinese origin, meaning 'peaceful' or 'still'"},
    {"name": "Qian", "meaning": "Chinese origin, meaning 'modest' or 'thousand'"},
    {"name": "Xia", "meaning": "Chinese origin, meaning 'summer' or 'glow of sunset'"},
    {"name": "Yue", "meaning": "Chinese origin, meaning 'moon'"},
    {"name": "Zhi", "meaning": "Chinese origin, meaning 'wisdom' or 'will'"},
    {"name": "Bao", "meaning": "Chinese origin, meaning 'treasure' or 'precious'"},
    {"name": "Fang", "meaning": "Chinese origin, meaning 'fragrant' or 'virtuous'"},
    {"name": "Jia", "meaning": "Chinese origin, meaning 'good' or 'beautiful'"},
    {"name": "Min", "meaning": "Chinese origin, meaning 'quick' or 'clever'"},
    {"name": "Rui", "meaning": "Chinese origin, meaning 'auspicious' or 'lucky'"},
    {"name": "Seul", "meaning": "Korean origin, meaning 'snow'"},
    {"name": "Soo", "meaning": "Korean origin, meaning 'excellent' or 'pure'"},
    {"name": "Yeon", "meaning": "Korean origin, meaning 'lotus' or 'beautiful'"},
    {"name": "Jiyeon", "meaning": "Korean origin, meaning 'wisdom' and 'beautiful'"},
    {"name": "Minji", "meaning": "Korean origin, meaning 'clever' and 'wisdom'"},
    {"name": "Jisoo", "meaning": "Korean origin, meaning 'wisdom' and 'excellent'"},
    {"name": "Hyejin", "meaning": "Korean origin, meaning 'grace' and 'precious'"},
    {"name": "Chaeyeon", "meaning": "Korean origin, meaning 'colorful' and 'beautiful'"},
    {"name": "Eunji", "meaning": "Korean origin, meaning 'silver' and 'wisdom'"},
    {"name": "Sooyeon", "meaning": "Korean origin, meaning 'pure' and 'beautiful'"},
]

# Load existing partial girls
import json

with open("/home/user/workspace/nameswipe/partial_girls.json") as f:
    g1 = json.load(f)
with open("/home/user/workspace/nameswipe/more_girls_partial2.json") as f:
    g2 = json.load(f)

all_girls = g1 + g2 + additional_girls

seen = set()
unique_girls = []
for n in all_girls:
    if n["name"].lower() not in seen:
        seen.add(n["name"].lower())
        unique_girls.append(n)

print(f"Total unique girl names: {len(unique_girls)}")
with open("/home/user/workspace/nameswipe/girl_names_research.json", "w") as f:
    json.dump(unique_girls, f, indent=2, ensure_ascii=False)
print("Girl names saved.")
