import json

final_girls = [
    # More vintage/classic
    {"name": "Geraldine", "meaning": "Old Germanic origin, meaning 'ruler with spear'"},
    {"name": "Gwendolyn", "meaning": "Welsh origin, meaning 'white circle' or 'blessed ring'"},
    {"name": "Hildegard", "meaning": "Old Germanic origin, meaning 'battle stronghold'"},
    {"name": "Honoria", "meaning": "Latin origin, meaning 'honor' or 'woman of honor'"},
    {"name": "Iphigenia", "meaning": "Greek origin, meaning 'born strong'"},
    {"name": "Isadora", "meaning": "Greek origin, meaning 'gift of Isis'"},
    {"name": "Isolde", "meaning": "Celtic origin, meaning 'ice ruler'"},
    {"name": "Jacinta", "meaning": "Spanish origin, from the hyacinth flower"},
    {"name": "Jessamine", "meaning": "Persian origin, from the jasmine flower"},
    {"name": "Josepha", "meaning": "Hebrew origin, feminine of Joseph, meaning 'God will add'"},
    {"name": "Juno", "meaning": "Latin origin, name of the Roman queen of gods"},
    {"name": "Justina", "meaning": "Latin origin, meaning 'just' or 'righteous'"},
    {"name": "Lavinia", "meaning": "Latin origin, meaning 'woman from Lavinium'"},
    {"name": "Leontine", "meaning": "Latin origin, meaning 'lion-like'"},
    {"name": "Leticia", "meaning": "Latin origin, meaning 'happiness' or 'joy'"},
    {"name": "Lorelei", "meaning": "German origin, from a Rhine River legend, meaning 'lurking rock'"},
    {"name": "Lottie", "meaning": "French origin, diminutive of Charlotte, meaning 'free woman'"},
    {"name": "Louisa", "meaning": "French form of Louise, meaning 'renowned warrior'"},
    {"name": "Lucinda", "meaning": "Latin origin, meaning 'light'"},
    {"name": "Luella", "meaning": "Old Germanic origin, meaning 'famous elf'"},
    {"name": "Lysandra", "meaning": "Greek origin, meaning 'liberator of men'"},
    {"name": "Madrigal", "meaning": "Italian origin, from the musical composition form"},
    {"name": "Magdalene", "meaning": "Hebrew origin, meaning 'woman from Magdala'"},
    {"name": "Maura", "meaning": "Celtic and Latin origin, meaning 'dark' or 'great'"},
    {"name": "Maureen", "meaning": "Irish form of Mary, meaning 'beloved'"},
    {"name": "Maxine", "meaning": "Latin origin, meaning 'greatest'"},
    {"name": "Mehetabel", "meaning": "Hebrew origin, meaning 'benefited by God'"},
    {"name": "Melisande", "meaning": "Germanic origin, meaning 'strong worker'"},
    {"name": "Melodie", "meaning": "Greek origin, meaning 'melody' or 'song'"},
    {"name": "Mercy", "meaning": "Latin origin, meaning 'compassion' or 'mercy'"},
    {"name": "Modesty", "meaning": "Latin origin, meaning 'moderate' or 'humble'"},
    {"name": "Moira", "meaning": "Irish form of Mary, meaning 'beloved'"},
    {"name": "Muriel", "meaning": "Celtic origin, meaning 'sea bright'"},
    {"name": "Myrna", "meaning": "Irish and Arabic origin, meaning 'tender' or 'beloved'"},
    {"name": "Nadya", "meaning": "Slavic origin, meaning 'hope'"},
    {"name": "Nelly", "meaning": "Greek origin, short for Helen, meaning 'bright'"},
    {"name": "Nerissa", "meaning": "Greek origin, meaning 'sea nymph'"},
    {"name": "Ninette", "meaning": "French origin, meaning 'little grace'"},
    {"name": "Noel", "meaning": "French origin, meaning 'born at Christmas'"},
    {"name": "Octavia", "meaning": "Latin origin, meaning 'eighth'"},
    {"name": "Odelia", "meaning": "Hebrew origin, meaning 'praise God'"},
    {"name": "Odile", "meaning": "Old Germanic origin, meaning 'wealth'"},
    {"name": "Olympia", "meaning": "Greek origin, meaning 'from Mount Olympus'"},
    {"name": "Ophelia", "meaning": "Greek origin, meaning 'help' or 'benefit'"},
    {"name": "Orinthia", "meaning": "Greek origin, meaning 'to stir' or 'excite'"},
    {"name": "Ottoline", "meaning": "Old Germanic origin, meaning 'little wealthy one'"},
    {"name": "Patience", "meaning": "Latin origin, meaning 'patient' or 'enduring'"},
    {"name": "Pauline", "meaning": "Latin origin, meaning 'small'"},
    {"name": "Petronella", "meaning": "Latin origin, diminutive of Petronia, meaning 'rock'"},
    {"name": "Philippa", "meaning": "Greek origin, meaning 'horse lover'"},
    {"name": "Philomena", "meaning": "Greek origin, meaning 'lover of strength'"},
    {"name": "Phryne", "meaning": "Greek origin, meaning 'toad' or 'speckled one'"},
    {"name": "Prudence", "meaning": "Latin origin, meaning 'prudent' or 'cautious'"},
    {"name": "Ramona", "meaning": "Spanish origin, meaning 'wise protector'"},
    {"name": "Raphaela", "meaning": "Hebrew origin, feminine of Raphael, meaning 'God has healed'"},
    {"name": "Rosamund", "meaning": "Old Germanic origin, meaning 'horse protector'"},
    {"name": "Rosalind", "meaning": "Old Germanic origin, meaning 'tender horse'"},
    {"name": "Rosalie", "meaning": "French form of Rosa, meaning 'rose'"},
    {"name": "Rosalba", "meaning": "Italian origin, meaning 'white rose'"},
    {"name": "Rosette", "meaning": "French diminutive of Rose, meaning 'little rose'"},
    {"name": "Rowena", "meaning": "Welsh origin, meaning 'white spear' or 'slender'"},
    {"name": "Roxane", "meaning": "Persian origin, meaning 'dawn' or 'luminous'"},
    {"name": "Rufina", "meaning": "Latin origin, meaning 'red-haired'"},
    {"name": "Salome", "meaning": "Hebrew origin, meaning 'peace'"},
    {"name": "Scholastica", "meaning": "Latin origin, meaning 'scholarly'"},
    {"name": "Selina", "meaning": "Greek origin, meaning 'moon'"},
    {"name": "Serena", "meaning": "Latin origin, meaning 'tranquil' or 'calm'"},
    {"name": "Sibyl", "meaning": "Greek origin, meaning 'prophetess'"},
    {"name": "Sidonia", "meaning": "Phoenician origin, meaning 'from Sidon'"},
    {"name": "Sigrid", "meaning": "Old Norse origin, meaning 'victory' and 'beautiful'"},
    {"name": "Solange", "meaning": "French origin, meaning 'solemn' or 'dignified'"},
    {"name": "Sophronia", "meaning": "Greek origin, meaning 'prudent' or 'sensible'"},
    {"name": "Sylvia", "meaning": "Latin origin, meaning 'forest' or 'woods'"},
    {"name": "Tamsin", "meaning": "English origin, short form of Thomasina, meaning 'twin'"},
    {"name": "Tansy", "meaning": "Greek origin, from the tansy plant, meaning 'immortality'"},
    {"name": "Temperance", "meaning": "Latin origin, meaning 'moderation' or 'temperance'"},
    {"name": "Thekla", "meaning": "Greek origin, meaning 'God's glory'"},
    {"name": "Thomasina", "meaning": "Aramaic origin, feminine of Thomas, meaning 'twin'"},
    {"name": "Vashti", "meaning": "Persian origin, meaning 'beautiful' or 'thread'"},
    {"name": "Venice", "meaning": "Latin origin, from the Italian city of Venice"},
    {"name": "Violetta", "meaning": "Italian form of Violet, meaning 'purple flower'"},
    {"name": "Walburga", "meaning": "Old Germanic origin, meaning 'strong protection'"},
    {"name": "Wilhelmina", "meaning": "Old Germanic origin, meaning 'determined protector'"},
    {"name": "Xenia", "meaning": "Greek origin, meaning 'hospitality'"},
    {"name": "Yetta", "meaning": "Hebrew origin, meaning 'plenty' or 'abundance'"},
    {"name": "Zenobia", "meaning": "Greek origin, meaning 'life of Zeus'"},

    # More modern names
    {"name": "Adalynn", "meaning": "Old Germanic origin, meaning 'noble' or 'nobility'"},
    {"name": "Adaline", "meaning": "Old Germanic origin, meaning 'noble'"},
    {"name": "Addilynn", "meaning": "Modern variant of Adeline, meaning 'noble'"},
    {"name": "Aiden", "meaning": "Irish origin, feminine use, meaning 'little fire'"},
    {"name": "Ainsley", "meaning": "Old English origin, meaning 'one's own meadow'"},
    {"name": "Aitana", "meaning": "Spanish origin, from a mountain in Valencia"},
    {"name": "Alaia", "meaning": "Basque origin, meaning 'joyful' or 'happy'"},
    {"name": "Alani", "meaning": "Hawaiian origin, meaning 'orange tree'"},
    {"name": "Alara", "meaning": "Turkish origin, meaning 'water fairy'"},
    {"name": "Alaya", "meaning": "Hebrew origin, meaning 'to ascend'"},
    {"name": "Alessa", "meaning": "Italian short form of Alessandra, meaning 'defender'"},
    {"name": "Alessia", "meaning": "Italian form of Alexia, meaning 'defender'"},
    {"name": "Alicia", "meaning": "Spanish form of Alice, meaning 'noble'"},
    {"name": "Alina", "meaning": "Slavic origin, meaning 'bright' or 'beautiful'"},
    {"name": "Alix", "meaning": "French form of Alice, meaning 'noble'"},
    {"name": "Aliza", "meaning": "Hebrew origin, meaning 'joyful'"},
    {"name": "Allegra", "meaning": "Italian and Latin origin, meaning 'joyful' or 'lively'"},
    {"name": "Allura", "meaning": "Latin origin, meaning 'to allure' or 'attraction'"},
    {"name": "Alondra", "meaning": "Spanish origin, meaning 'lark'"},
    {"name": "Alora", "meaning": "Latin and African origin, meaning 'my dream'"},
    {"name": "Alva", "meaning": "Norse and Latin origin, meaning 'elf' or 'white'"},
    {"name": "Alvina", "meaning": "Old English origin, meaning 'noble friend'"},
    {"name": "Alyana", "meaning": "Native American origin, meaning 'eternal bloom'"},
    {"name": "Amaia", "meaning": "Basque origin, meaning 'the end'"},
    {"name": "Amari", "meaning": "Yoruba and Hebrew origin, meaning 'strength' or 'grace'"},
    {"name": "Amaris", "meaning": "Hebrew origin, meaning 'given by God'"},
    {"name": "Amaya", "meaning": "Japanese and Basque origin, meaning 'night rain'"},
    {"name": "Amber", "meaning": "Arabic origin, meaning 'jewel'"},
    {"name": "Amberly", "meaning": "English origin, combining Amber and the suffix -ly"},
    {"name": "Amora", "meaning": "Spanish origin, meaning 'love'"},
    {"name": "Amorie", "meaning": "Latin and French origin, meaning 'love'"},
    {"name": "Amylia", "meaning": "Latin origin, variant of Amelia, meaning 'hardworking'"},
    {"name": "Analia", "meaning": "Hebrew and Latin origin, meaning 'grace' and 'light'"},
    {"name": "Anaya", "meaning": "Hebrew origin, meaning 'God answered'"},
    {"name": "Andalucia", "meaning": "Spanish origin, from the region of Andalusia"},
    {"name": "Andromeda", "meaning": "Greek mythological name, meaning 'ruler of men'"},
    {"name": "Anela", "meaning": "Hawaiian origin, meaning 'angel' or 'messenger'"},
    {"name": "Angelica", "meaning": "Latin origin, meaning 'angelic' or 'like an angel'"},
    {"name": "Angelina", "meaning": "Latin origin, meaning 'little angel'"},
    {"name": "Anika", "meaning": "Sanskrit origin, meaning 'grace'"},
    {"name": "Aniyah", "meaning": "Arabic origin, meaning 'caring' or 'concern'"},
    {"name": "Annalise", "meaning": "Hebrew and Latin combination, meaning 'grace' and 'God's oath'"},
    {"name": "Annora", "meaning": "Latin origin, meaning 'honor'"},
    {"name": "Antoinette", "meaning": "French form of Anthony, meaning 'priceless one'"},
    {"name": "Aoibheann", "meaning": "Irish origin, meaning 'beautiful sheen'"},
    {"name": "Aphrodite", "meaning": "Greek mythological name, goddess of love"},
    {"name": "Apollonia", "meaning": "Greek origin, meaning 'of Apollo'"},
    {"name": "Arabella", "meaning": "Latin origin, meaning 'yielding to prayer'"},
    {"name": "Araminta", "meaning": "Hebrew origin, meaning 'lofty'"},
    {"name": "Arcadia", "meaning": "Greek origin, meaning 'pastoral paradise'"},
    {"name": "Ardea", "meaning": "Latin origin, name of an ancient city"},
    {"name": "Ardella", "meaning": "Hebrew origin, meaning 'flowering field'"},
    {"name": "Arella", "meaning": "Hebrew origin, meaning 'angel' or 'messenger'"},
    {"name": "Areta", "meaning": "Greek origin, meaning 'excellence' or 'virtue'"},
    {"name": "Arethusa", "meaning": "Greek origin, name of a water nymph"},
    {"name": "Argenta", "meaning": "Latin origin, meaning 'silver'"},
    {"name": "Argyle", "meaning": "Scottish Gaelic origin, meaning 'from the land of the Gaels'"},
    {"name": "Ariella", "meaning": "Hebrew origin, meaning 'lion of God'"},
    {"name": "Arielle", "meaning": "French form of Ariel, meaning 'lion of God'"},
    {"name": "Arietta", "meaning": "Italian origin, meaning 'little aria' or 'little song'"},
    {"name": "Ariya", "meaning": "Sanskrit and Hebrew origin, meaning 'noble' or 'lioness'"},
    {"name": "Arla", "meaning": "Old English origin, meaning 'hare meadow'"},
    {"name": "Arlene", "meaning": "Celtic origin, meaning 'pledge'"},
    {"name": "Arlo", "meaning": "Spanish origin, meaning 'barberry tree' (modern unisex use)"},
    {"name": "Armani", "meaning": "Italian origin, meaning 'free man'"},
    {"name": "Armelle", "meaning": "Breton origin, meaning 'princess stone'"},
    {"name": "Arnelle", "meaning": "Old Germanic origin, meaning 'eagle power'"},
    {"name": "Arwen", "meaning": "Welsh origin, meaning 'noble maiden'"},
    {"name": "Arya", "meaning": "Sanskrit origin, meaning 'noble' or 'honorable'"},
    {"name": "Ashleigh", "meaning": "Old English origin, meaning 'ash tree meadow'"},
    {"name": "Aspen", "meaning": "Old English nature name referring to the aspen tree"},
    {"name": "Aspyn", "meaning": "Modern variant of Aspen, meaning 'aspen tree'"},
    {"name": "Assunta", "meaning": "Italian origin, meaning 'assumed into heaven'"},
    {"name": "Astoria", "meaning": "Greek origin, meaning 'of the stars'"},
    {"name": "Atalanta", "meaning": "Greek mythological name, meaning 'secure'"},
    {"name": "Atarah", "meaning": "Hebrew origin, meaning 'crown'"},
    {"name": "Athalia", "meaning": "Hebrew origin, meaning 'God is exalted'"},
    {"name": "Athanasia", "meaning": "Greek origin, meaning 'immortality'"},
    {"name": "Atlanta", "meaning": "Greek origin, from the mythological figure Atalanta"},
    {"name": "Atlanna", "meaning": "Modern invented name, possibly inspired by Atalanta"},
    {"name": "Auberon", "meaning": "Old Germanic origin, meaning 'noble bear'"},
    {"name": "Aude", "meaning": "Old Germanic origin, meaning 'wealth'"},
    {"name": "Audriana", "meaning": "Modern combination of Audrey and Ana"},
    {"name": "Audrienne", "meaning": "Old English origin, meaning 'noble strength'"},
    {"name": "Auriana", "meaning": "Latin origin, meaning 'golden'"},
    {"name": "Auriella", "meaning": "Latin origin, meaning 'little golden one'"},
    {"name": "Aurika", "meaning": "Latin origin, meaning 'gold'"},
    {"name": "Avabelle", "meaning": "Latin and French combination, meaning 'beautiful bird'"},
    {"name": "Avaery", "meaning": "Modern variant of Avery, meaning 'elf ruler'"},
    {"name": "Avah", "meaning": "Hebrew origin, variant of Ava, meaning 'life'"},
    {"name": "Avalon", "meaning": "Celtic origin, meaning 'island of apples'"},
    {"name": "Avara", "meaning": "Hebrew origin, meaning 'father of multitudes'"},
    {"name": "Aveline", "meaning": "Old French origin, meaning 'hazelnut'"},
    {"name": "Averie", "meaning": "Old English origin, variant of Avery, meaning 'elf ruler'"},
    {"name": "Averly", "meaning": "Modern variant of Avery and Beverly"},
    {"name": "Avery", "meaning": "Old Germanic origin, meaning 'elf ruler'"},
    {"name": "Aviana", "meaning": "Latin origin, meaning 'bird'"},
    {"name": "Aviela", "meaning": "Hebrew origin, meaning 'God is my father'"},
    {"name": "Aviella", "meaning": "Hebrew origin, meaning 'God is my father'"},
    {"name": "Aviva", "meaning": "Hebrew origin, meaning 'spring' or 'youthful'"},
    {"name": "Azalea", "meaning": "Greek origin, from the azalea flower"},
    {"name": "Azora", "meaning": "Hebrew origin, meaning 'helped by God'"},
    {"name": "Azaria", "meaning": "Hebrew origin, meaning 'helped by God'"},
    {"name": "Azure", "meaning": "French origin, meaning 'sky blue'"},
    {"name": "Becca", "meaning": "Hebrew origin, short form of Rebecca, meaning 'to bind'"},
    {"name": "Bel", "meaning": "Hebrew origin, short form of Isabel or Arabella"},
    {"name": "Bellatrix", "meaning": "Latin origin, meaning 'female warrior'"},
    {"name": "Bellamy", "meaning": "Old French origin, meaning 'good friend'"},
    {"name": "Bexley", "meaning": "Old English origin, meaning 'box tree meadow'"},
    {"name": "Biana", "meaning": "Latin origin, meaning 'white'"},
    {"name": "Bijou", "meaning": "French origin, meaning 'jewel'"},
    {"name": "Blair", "meaning": "Scottish Gaelic origin, meaning 'plain' or 'field'"},
    {"name": "Blakely", "meaning": "Old English origin, meaning 'dark' or 'pale meadow'"},
    {"name": "Blakely", "meaning": "Old English origin, meaning 'dark or pale meadow'"},
    {"name": "Blanca", "meaning": "Spanish origin, meaning 'white' or 'fair'"},
    {"name": "Blythe", "meaning": "Old English origin, meaning 'happy' or 'carefree'"},
    {"name": "Bo", "meaning": "Scandinavian origin, meaning 'to live' or 'to dwell'"},
    {"name": "Braelyn", "meaning": "Modern invented name, possibly Irish-inspired"},
    {"name": "Brenley", "meaning": "Modern variant combining Brenna and Ashley"},
    {"name": "Brenna", "meaning": "Irish origin, meaning 'raven' or 'black-haired'"},
    {"name": "Bria", "meaning": "Irish origin, short form of Brianna, meaning 'strong'"},
    {"name": "Briar", "meaning": "Old English nature name referring to thorny plants"},
    {"name": "Brinley", "meaning": "Old English origin, meaning 'burnt meadow'"},
    {"name": "Bristol", "meaning": "Old English origin, meaning 'site of the bridge'"},
    {"name": "Bronwyn", "meaning": "Welsh origin, meaning 'white breast'"},
    {"name": "Brylee", "meaning": "Modern invented name, variant of Riley"},
    {"name": "Cadence", "meaning": "Latin origin, meaning 'rhythm' or 'flow'"},
    {"name": "Caleigh", "meaning": "Irish origin, variant of Kaylee, meaning 'pure'"},
    {"name": "Calico", "meaning": "English origin, from the cotton fabric"},
    {"name": "Cambria", "meaning": "Latin origin, meaning 'from Wales'"},
    {"name": "Camryn", "meaning": "Scottish Gaelic origin, variant of Cameron, meaning 'crooked nose'"},
    {"name": "Capri", "meaning": "Italian origin, from the island of Capri"},
    {"name": "Caprice", "meaning": "Italian origin, meaning 'whim' or 'fancy'"},
    {"name": "Carina", "meaning": "Latin origin, meaning 'keel of a boat' or 'dear little one'"},
    {"name": "Carys", "meaning": "Welsh origin, meaning 'love'"},
    {"name": "Cassidy", "meaning": "Irish origin, meaning 'curly-haired'"},
    {"name": "Cattleya", "meaning": "Latin origin, from the cattleya orchid"},
    {"name": "Caylee", "meaning": "Modern variant of Kaylee, meaning 'pure'"},
    {"name": "Cecily", "meaning": "Latin origin, meaning 'blind'"},
    {"name": "Celine", "meaning": "Latin and French origin, meaning 'heavenly'"},
    {"name": "Cezanne", "meaning": "French surname used as a first name"},
    {"name": "Chandra", "meaning": "Sanskrit origin, meaning 'moon'"},
    {"name": "Chandler", "meaning": "Old French origin, meaning 'candle maker'"},
    {"name": "Charlize", "meaning": "South African variant of Charlotte, meaning 'free woman'"},
    {"name": "Charmian", "meaning": "Greek origin, meaning 'joy' or 'delight'"},
    {"name": "Chassidy", "meaning": "Modern variant of Cassidy, meaning 'curly-haired'"},
    {"name": "Chaya", "meaning": "Hebrew origin, meaning 'life'"},
    {"name": "Chelsea", "meaning": "Old English origin, meaning 'chalk landing place'"},
    {"name": "Cheyenne", "meaning": "Native American origin, meaning 'people of a different language'"},
    {"name": "Chiara", "meaning": "Italian origin, meaning 'bright' or 'clear'"},
    {"name": "Chloelle", "meaning": "Modern variant of Chloe, meaning 'blooming'"},
    {"name": "Chrissy", "meaning": "Greek origin, short for Christine, meaning 'follower of Christ'"},
    {"name": "Cinderella", "meaning": "French origin, meaning 'little ash girl'"},
    {"name": "Cinta", "meaning": "Spanish origin, meaning 'belt' or 'ribbon'"},
    {"name": "Citlali", "meaning": "Nahuatl origin, meaning 'star'"},
    {"name": "Clairette", "meaning": "French origin, diminutive of Claire, meaning 'clear'"},
    {"name": "Clarity", "meaning": "Latin origin, meaning 'clearness' or 'brightness'"},
    {"name": "Claudette", "meaning": "French form of Claudia, meaning 'lame'"},
    {"name": "Claudine", "meaning": "French form of Claudia, meaning 'lame'"},
    {"name": "Clem", "meaning": "Latin origin, short for Clementine, meaning 'gentle'"},
    {"name": "Clementina", "meaning": "Latin origin, meaning 'gentle' or 'merciful'"},
    {"name": "Clover", "meaning": "Old English nature name from the clover plant"},
    {"name": "Colette", "meaning": "French form of Nicolette, meaning 'victory'"},
    {"name": "Coni", "meaning": "Latin origin, short form of Concetta"},
    {"name": "Corazon", "meaning": "Spanish origin, meaning 'heart'"},
    {"name": "Corinna", "meaning": "Greek origin, meaning 'maiden'"},
    {"name": "Cosima", "meaning": "Italian form of Cosmas, meaning 'order' or 'beauty'"},
    {"name": "Couture", "meaning": "French origin, meaning 'sewing' or 'fashion'"},
    {"name": "Crystalina", "meaning": "Latin and Greek origin, meaning 'sparkling'"},
    {"name": "Cuba", "meaning": "Spanish origin, from the island nation"},
    {"name": "Cymbeline", "meaning": "Celtic origin, meaning 'lord of the sun'"},
    {"name": "Cynara", "meaning": "Greek origin, meaning 'artichoke plant'"},
    {"name": "Cynthia", "meaning": "Greek origin, epithet of Artemis, meaning 'from Mount Cynthus'"},
    {"name": "Dagny", "meaning": "Old Norse origin, meaning 'new day'"},
    {"name": "Dahlia", "meaning": "Swedish origin, from the dahlia flower"},
    {"name": "Daisy", "meaning": "Old English nature name meaning 'day's eye'"},
    {"name": "Dakota", "meaning": "Sioux origin, meaning 'friend' or 'ally'"},
    {"name": "Dallas", "meaning": "Scottish Gaelic origin, meaning 'from the valley meadow'"},
    {"name": "Dani", "meaning": "Hebrew origin, short form of Daniela, meaning 'God is my judge'"},
    {"name": "Daniela", "meaning": "Hebrew origin, meaning 'God is my judge'"},
    {"name": "Danika", "meaning": "Slavic origin, meaning 'morning star'"},
    {"name": "Danna", "meaning": "Hebrew origin, meaning 'God is my judge'"},
    {"name": "Daphne", "meaning": "Greek origin, meaning 'laurel tree'"},
    {"name": "Darci", "meaning": "Irish origin, meaning 'dark one'"},
    {"name": "Darla", "meaning": "Old English origin, meaning 'darling'"},
    {"name": "Darlene", "meaning": "English origin, meaning 'darling' or 'tenderly beloved'"},
    {"name": "Davina", "meaning": "Scottish feminine form of David, meaning 'beloved'"},
    {"name": "Dawn", "meaning": "Old English nature name meaning 'daybreak'"},
    {"name": "Dayla", "meaning": "Hebrew origin, meaning 'branch' or 'vine of God'"},
    {"name": "Dayna", "meaning": "Scandinavian origin, meaning 'from Denmark'"},
    {"name": "Deja", "meaning": "French origin, meaning 'already' or 'before'"},
    {"name": "Delara", "meaning": "Persian origin, meaning 'that which adorns the heart'"},
    {"name": "Delia", "meaning": "Greek origin, meaning 'from Delos'"},
    {"name": "Demi", "meaning": "Greek origin, meaning 'half' or 'small'"},
    {"name": "Devyn", "meaning": "Irish origin, meaning 'poet' or 'bard'"},
]

# Load existing girl names
with open("/home/user/workspace/nameswipe/girl_names_research.json") as f:
    existing = json.load(f)

all_girls = existing + final_girls

seen = set()
unique_girls = []
for n in all_girls:
    if n["name"].lower() not in seen:
        seen.add(n["name"].lower())
        unique_girls.append(n)

print(f"Total unique girl names: {len(unique_girls)}")
with open("/home/user/workspace/nameswipe/girl_names_research.json", "w") as f:
    json.dump(unique_girls, f, indent=2, ensure_ascii=False)
print("Girl names saved.")
