import json

# Final batch to push girl names over 2000
last_batch = [
    {"name": "Diana", "meaning": "Latin origin, Roman goddess of the moon, meaning 'divine'"},
    {"name": "Diane", "meaning": "French form of Diana, meaning 'divine moon goddess'"},
    {"name": "Diandra", "meaning": "Greek origin, meaning 'divine woman'"},
    {"name": "Diantha", "meaning": "Greek origin, meaning 'divine flower'"},
    {"name": "Dior", "meaning": "French origin, from the fashion house name"},
    {"name": "Dixie", "meaning": "French origin, meaning 'tenth' or 'southern'"},
    {"name": "Domenica", "meaning": "Italian origin, meaning 'born on Sunday'"},
    {"name": "Dominique", "meaning": "French origin, meaning 'belonging to the Lord'"},
    {"name": "Donatella", "meaning": "Italian origin, meaning 'gift'"},
    {"name": "Donella", "meaning": "Scottish Gaelic origin, meaning 'world ruler'"},
    {"name": "Dora", "meaning": "Greek origin, meaning 'gift'"},
    {"name": "Dorina", "meaning": "Greek origin, diminutive of Dora, meaning 'gift'"},
    {"name": "Drucilla", "meaning": "Latin origin, meaning 'strong'"},
    {"name": "Dulcinea", "meaning": "Spanish origin, meaning 'sweetness'"},
    {"name": "Ebony", "meaning": "Egyptian origin, meaning 'black wood'"},
    {"name": "Eden", "meaning": "Hebrew origin, meaning 'paradise' or 'delight'"},
    {"name": "Edie", "meaning": "Old English origin, short form of Edith, meaning 'prosperous'"},
    {"name": "Edwina", "meaning": "Old English origin, meaning 'wealthy friend'"},
    {"name": "Effie", "meaning": "Greek origin, short for Euphemia, meaning 'well-spoken'"},
    {"name": "Elan", "meaning": "Hebrew and Native American origin, meaning 'tree' or 'friendly'"},
    {"name": "Elana", "meaning": "Hebrew origin, meaning 'tree'"},
    {"name": "Elara", "meaning": "Greek origin, one of Jupiter's moons"},
    {"name": "Eleanora", "meaning": "Greek origin, meaning 'shining light'"},
    {"name": "Elektra", "meaning": "Greek origin, meaning 'amber' or 'bright'"},
    {"name": "Elena", "meaning": "Greek and Spanish origin, meaning 'shining light'"},
    {"name": "Eleni", "meaning": "Greek origin, meaning 'torch' or 'shining light'"},
    {"name": "Eleonor", "meaning": "Greek and French origin, meaning 'bright' or 'shining'"},
    {"name": "Eleri", "meaning": "Welsh origin, from a river name"},
    {"name": "Elfleda", "meaning": "Old English origin, meaning 'elf beauty'"},
    {"name": "Eliana", "meaning": "Hebrew and Italian origin, meaning 'my God has answered'"},
    {"name": "Elianna", "meaning": "Hebrew origin, meaning 'God has answered me'"},
    {"name": "Elinda", "meaning": "Modern combination of Elena and Linda"},
    {"name": "Elinor", "meaning": "Welsh form of Eleanor, meaning 'shining light'"},
    {"name": "Elisa", "meaning": "Hebrew origin, short form of Elizabeth, meaning 'God's oath'"},
    {"name": "Elise", "meaning": "French short form of Elizabeth, meaning 'God's oath'"},
    {"name": "Elisha", "meaning": "Hebrew origin, meaning 'God is salvation'"},
    {"name": "Elissa", "meaning": "Greek and Hebrew origin, meaning 'rational'"},
    {"name": "Eliza", "meaning": "Hebrew origin, short form of Elizabeth, meaning 'God's oath'"},
    {"name": "Elke", "meaning": "Old Germanic origin, meaning 'noble'"},
    {"name": "Ella", "meaning": "Old Germanic origin, meaning 'all' or 'completely'"},
    {"name": "Ellena", "meaning": "Greek origin, variant of Helena, meaning 'shining light'"},
    {"name": "Ellenora", "meaning": "Greek origin, variant of Eleanor, meaning 'shining one'"},
    {"name": "Ellery", "meaning": "Old English origin, meaning 'island with elder trees'"},
    {"name": "Elliana", "meaning": "Hebrew origin, meaning 'my God has answered'"},
    {"name": "Elliot", "meaning": "Hebrew origin via English, meaning 'Jehovah is God'"},
    {"name": "Elliotte", "meaning": "Modern feminine form of Elliott"},
    {"name": "Elma", "meaning": "Turkish and Greek origin, meaning 'apple'"},
    {"name": "Elna", "meaning": "Scandinavian origin, short form of Elena, meaning 'light'"},
    {"name": "Elnora", "meaning": "Greek origin, meaning 'light' or 'shining'"},
    {"name": "Eloda", "meaning": "Greek origin, meaning 'marsh flower'"},
    {"name": "Elodie", "meaning": "French origin, meaning 'foreign riches'"},
    {"name": "Eloisa", "meaning": "Spanish form of Eloise, meaning 'famous warrior'"},
    {"name": "Eloise", "meaning": "Old French origin, meaning 'famous warrior'"},
    {"name": "Elora", "meaning": "Hebrew origin, meaning 'my God is light'"},
    {"name": "Elowen", "meaning": "Cornish origin, meaning 'elm tree'"},
    {"name": "Elpida", "meaning": "Greek origin, meaning 'hope'"},
    {"name": "Elsa", "meaning": "German short form of Elizabeth, meaning 'God's oath'"},
    {"name": "Elsie", "meaning": "Scottish short form of Elizabeth, meaning 'God's oath'"},
    {"name": "Elvina", "meaning": "Old English origin, meaning 'elf friend'"},
    {"name": "Elvira", "meaning": "Spanish and Germanic origin, meaning 'all true'"},
    {"name": "Elyse", "meaning": "French form of Elizabeth, meaning 'God's oath'"},
    {"name": "Elysia", "meaning": "Latin origin, from Elysium, meaning 'blissful'"},
    {"name": "Emerald", "meaning": "Greek origin, from the green gemstone"},
    {"name": "Emilee", "meaning": "Latin origin, variant of Emily, meaning 'rival'"},
    {"name": "Emilia", "meaning": "Latin origin, meaning 'rival' or 'to excel'"},
    {"name": "Emiliana", "meaning": "Latin origin, meaning 'rival' or 'to strive'"},
    {"name": "Emilienne", "meaning": "French form of Emilia, meaning 'to excel'"},
    {"name": "Emillia", "meaning": "Latin origin, variant spelling of Emilia"},
    {"name": "Emma", "meaning": "Old Germanic origin, meaning 'whole' or 'universal'"},
    {"name": "Emmanuelle", "meaning": "Hebrew origin via French, meaning 'God is with us'"},
    {"name": "Emmy", "meaning": "Old Germanic origin, diminutive of Emma"},
    {"name": "Emory", "meaning": "Old Germanic origin, meaning 'brave' or 'powerful ruler'"},
    {"name": "Ena", "meaning": "Irish origin, short form of Eithne, meaning 'kernel'"},
    {"name": "Encarna", "meaning": "Spanish origin, meaning 'incarnation'"},
    {"name": "Endellion", "meaning": "Cornish origin, from a Cornish saint's name"},
    {"name": "Enid", "meaning": "Welsh origin, meaning 'life' or 'spirit'"},
    {"name": "Eowyn", "meaning": "Old English origin, meaning 'horse joy'"},
    {"name": "Epiphany", "meaning": "Greek origin, meaning 'manifestation'"},
    {"name": "Erina", "meaning": "Irish origin, from Eire, meaning 'from Ireland'"},
    {"name": "Eris", "meaning": "Greek origin, goddess of discord, meaning 'strife'"},
    {"name": "Esme", "meaning": "Old French origin, meaning 'beloved' or 'esteemed'"},
    {"name": "Esmee", "meaning": "French origin, meaning 'beloved'"},
    {"name": "Esmeralda", "meaning": "Spanish and Portuguese origin, meaning 'emerald'"},
    {"name": "Estella", "meaning": "Latin origin, meaning 'star'"},
    {"name": "Estelle", "meaning": "Latin and French origin, meaning 'star'"},
    {"name": "Eudora", "meaning": "Greek origin, meaning 'good gift'"},
    {"name": "Eugenie", "meaning": "French form of Eugenia, meaning 'well-born'"},
    {"name": "Eulalia", "meaning": "Greek origin, meaning 'sweetly spoken'"},
    {"name": "Eunice", "meaning": "Greek origin, meaning 'good victory'"},
    {"name": "Euphemia", "meaning": "Greek origin, meaning 'well-spoken'"},
    {"name": "Eurydice", "meaning": "Greek mythological name, meaning 'wide justice'"},
    {"name": "Eva", "meaning": "Hebrew origin, meaning 'life' or 'living'"},
    {"name": "Evander", "meaning": "Modern feminine use of the Greek name meaning 'good man'"},
    {"name": "Evangeline", "meaning": "Greek origin, meaning 'bearer of good news'"},
    {"name": "Evangelina", "meaning": "Greek origin, meaning 'good news'"},
    {"name": "Evanthia", "meaning": "Greek origin, meaning 'good flower'"},
    {"name": "Eve", "meaning": "Hebrew origin, meaning 'life' or 'living'"},
    {"name": "Evelia", "meaning": "Hebrew and Latin origin, meaning 'life' or 'lively'"},
    {"name": "Evelina", "meaning": "Hebrew and English origin, meaning 'life' or 'hazelnut'"},
    {"name": "Fabiola", "meaning": "Latin origin, feminine of Fabio, meaning 'bean farmer'"},
    {"name": "Fairley", "meaning": "Old English origin, meaning 'fair meadow'"},
    {"name": "Faith", "meaning": "Latin origin, meaning 'faith' or 'belief'"},
    {"name": "Fallon", "meaning": "Irish origin, meaning 'in charge'"},
    {"name": "Fallyn", "meaning": "Irish origin, variant of Fallon, meaning 'in charge'"},
    {"name": "Fancy", "meaning": "English origin, meaning 'imagination' or 'whim'"},
    {"name": "Farrah", "meaning": "Arabic origin, meaning 'joy' or 'happiness'"},
    {"name": "Fatou", "meaning": "West African form of Fatima, meaning 'captivating'"},
    {"name": "Fawn", "meaning": "Old French nature name meaning 'young deer'"},
    {"name": "Faye", "meaning": "Old French origin, meaning 'fairy'"},
    {"name": "Felicia", "meaning": "Latin origin, meaning 'happy' or 'fortunate'"},
    {"name": "Felicitas", "meaning": "Latin origin, meaning 'happiness' or 'good luck'"},
    {"name": "Feodora", "meaning": "Russian form of Theodora, meaning 'gift of God'"},
    {"name": "Fernanda", "meaning": "Spanish form of Ferdinanda, meaning 'bold voyager'"},
    {"name": "Fia", "meaning": "Irish and Italian origin, meaning 'wild deer' or 'flame'"},
    {"name": "Fifi", "meaning": "French diminutive of Josephine, meaning 'God will add'"},
    {"name": "Figen", "meaning": "Turkish origin, meaning 'fig tree'"},
    {"name": "Filippa", "meaning": "Italian form of Philippa, meaning 'horse lover'"},
    {"name": "Finley", "meaning": "Scottish Gaelic origin, meaning 'fair warrior'"},
    {"name": "Fiora", "meaning": "Italian origin, meaning 'flower'"},
    {"name": "Fiorella", "meaning": "Italian origin, meaning 'little flower'"},
    {"name": "Flavia", "meaning": "Latin origin, meaning 'golden-haired'"},
    {"name": "Floriana", "meaning": "Latin origin, meaning 'flowering'"},
    {"name": "Florian", "meaning": "Latin origin, meaning 'flowering' (modern unisex use)"},
    {"name": "Florrie", "meaning": "Latin origin, short form of Florence, meaning 'flourishing'"},
    {"name": "Flossy", "meaning": "English origin, diminutive of Florence, meaning 'flourishing'"},
    {"name": "Fontaine", "meaning": "French origin, meaning 'fountain'"},
    {"name": "Fortune", "meaning": "Latin origin, meaning 'luck' or 'fortune'"},
    {"name": "Francesca", "meaning": "Italian form of Frances, meaning 'Frenchwoman'"},
    {"name": "Francine", "meaning": "French form of Frances, meaning 'Frenchwoman'"},
    {"name": "Freda", "meaning": "Old Germanic origin, meaning 'peaceful ruler'"},
    {"name": "Frederica", "meaning": "Old Germanic origin, meaning 'peaceful ruler'"},
    {"name": "Freya", "meaning": "Old Norse origin, name of the goddess of love"},
    {"name": "Frida", "meaning": "Old Germanic origin, meaning 'peace'"},
    {"name": "Fritzi", "meaning": "German diminutive of Frederica, meaning 'peaceful ruler'"},
    {"name": "Gabi", "meaning": "Hebrew origin, short form of Gabriella, meaning 'God is my strength'"},
    {"name": "Gabriella", "meaning": "Hebrew origin, meaning 'God is my strength'"},
    {"name": "Gaia", "meaning": "Greek origin, name of the earth goddess, meaning 'earth'"},
    {"name": "Galatea", "meaning": "Greek origin, meaning 'milk-white'"},
    {"name": "Gale", "meaning": "Old English origin, meaning 'jovial'"},
    {"name": "Garnet", "meaning": "English origin, from the dark red gemstone"},
    {"name": "Garland", "meaning": "Old French origin, meaning 'wreath of flowers'"},
    {"name": "Gilda", "meaning": "Old Germanic origin, meaning 'sacrifice'"},
    {"name": "Ginevra", "meaning": "Italian form of Guinevere, meaning 'white shadow'"},
    {"name": "Giovanna", "meaning": "Italian form of Jane, meaning 'God is gracious'"},
    {"name": "Giulia", "meaning": "Italian form of Julia, meaning 'youthful'"},
    {"name": "Giuliana", "meaning": "Italian form of Juliana, meaning 'youthful'"},
    {"name": "Gladys", "meaning": "Welsh origin, meaning 'princess' or 'royalty'"},
    {"name": "Goldie", "meaning": "Old English origin, meaning 'made of gold'"},
    {"name": "Grace", "meaning": "Latin origin, meaning 'grace' or 'favor of God'"},
    {"name": "Gracie", "meaning": "Latin origin, diminutive of Grace, meaning 'grace'"},
    {"name": "Greer", "meaning": "Scottish origin, meaning 'watchful'"},
    {"name": "Greta", "meaning": "German short form of Margaret, meaning 'pearl'"},
    {"name": "Gretchen", "meaning": "German diminutive of Margaret, meaning 'pearl'"},
    {"name": "Grier", "meaning": "Scottish origin, meaning 'alert' or 'watchful'"},
    {"name": "Guadalupe", "meaning": "Spanish origin, meaning 'valley of wolves'"},
    {"name": "Guinevere", "meaning": "Welsh origin, meaning 'white shadow' or 'white wave'"},
    {"name": "Gunhild", "meaning": "Old Norse origin, meaning 'battle warrior'"},
    {"name": "Hadassah", "meaning": "Hebrew origin, meaning 'myrtle tree'"},
    {"name": "Haidee", "meaning": "Greek origin, possibly meaning 'caressed'"},
    {"name": "Hailey", "meaning": "Old English origin, meaning 'hay meadow'"},
    {"name": "Halia", "meaning": "Hawaiian origin, meaning 'remembrance of a loved one'"},
    {"name": "Hallie", "meaning": "Old Norse origin, meaning 'rock'"},
    {"name": "Hana", "meaning": "Japanese and Arabic origin, meaning 'flower' or 'bliss'"},
    {"name": "Hanna", "meaning": "Hebrew origin, meaning 'grace' or 'favor'"},
    {"name": "Harmony", "meaning": "Latin origin, meaning 'concord' or 'harmony'"},
    {"name": "Haven", "meaning": "Old English origin, meaning 'safe place'"},
    {"name": "Heavenly", "meaning": "English origin, meaning 'heavenly' or 'divine'"},
    {"name": "Heidi", "meaning": "German short form of Adelheid, meaning 'noble kind'"},
    {"name": "Helga", "meaning": "Old Norse origin, meaning 'holy' or 'blessed'"},
    {"name": "Hera", "meaning": "Greek origin, queen of the gods, meaning 'protectress'"},
    {"name": "Hermione", "meaning": "Greek origin, meaning 'messenger' or 'earthly'"},
    {"name": "Hillevi", "meaning": "Old Norse origin, meaning 'holy war'"},
    {"name": "Hope", "meaning": "Old English origin, meaning 'hope' or 'expectation'"},
    {"name": "Huxley", "meaning": "Old English origin, meaning 'Hugh's meadow'"},
    {"name": "Hypatia", "meaning": "Greek origin, meaning 'highest'"},
    {"name": "Idalia", "meaning": "Greek origin, meaning 'sun'"},
    {"name": "Idina", "meaning": "Hebrew or English origin, possibly meaning 'industrious'"},
    {"name": "Ilaria", "meaning": "Italian form of Hilary, meaning 'cheerful'"},
    {"name": "Ilinca", "meaning": "Romanian form of Elena, meaning 'shining light'"},
    {"name": "Ilona", "meaning": "Hungarian form of Helen, meaning 'shining light'"},
    {"name": "Ilse", "meaning": "German short form of Elizabeth, meaning 'God's oath'"},
    {"name": "Imara", "meaning": "Swahili origin, meaning 'strong' or 'firm'"},
    {"name": "Imogen", "meaning": "Celtic origin, possibly meaning 'maiden'"},
    {"name": "Ines", "meaning": "Spanish and Portuguese form of Agnes, meaning 'pure'"},
    {"name": "Ingeborg", "meaning": "Old Norse origin, meaning 'Ing's fortress'"},
    {"name": "Ingrid", "meaning": "Old Norse origin, meaning 'Ing's beauty'"},
    {"name": "Iolanthe", "meaning": "Greek origin, meaning 'violet flower'"},
    {"name": "Ione", "meaning": "Greek origin, meaning 'violet flower'"},
    {"name": "Isolde", "meaning": "Celtic origin, meaning 'ice ruler'"},
    {"name": "Ista", "meaning": "Old English origin, meaning 'eastern'"},
]

with open("/home/user/workspace/nameswipe/girl_names_research.json") as f:
    existing = json.load(f)

all_girls = existing + last_batch

seen = set()
unique_girls = []
for n in all_girls:
    if n["name"].lower() not in seen:
        seen.add(n["name"].lower())
        unique_girls.append(n)

print(f"Total unique girl names: {len(unique_girls)}")
with open("/home/user/workspace/nameswipe/girl_names_research.json", "w") as f:
    json.dump(unique_girls, f, indent=2, ensure_ascii=False)
print("Girl names saved.")
